import type { ArticleContentProfile } from './articleSourceData'

type CuratedArticleMetadata = Pick<ArticleContentProfile, 'topic' | 'event' | 'summary' | 'facts' | 'affectedTargets' | 'damageTypes' | 'industries' | 'keywords' | 'signals' | 'reviewActions' | 'evidenceConfidence' | 'scores'> & {
  title: string
  source: string
  publishedAt?: string
  isRegulatory?: boolean
}

const profile = (input: Omit<CuratedArticleMetadata, 'title' | 'source'> & { title: string; source: string }): CuratedArticleMetadata => input

const laws = {
  employmentCollection: profile({
    title: '고용·산재보험료 징수 법률', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '고용보험과 산업재해보상보험의 보험관계 성립·소멸, 보험료 산정·신고·납부 기준을 정하는 법률입니다.',
    summary: '사업주·근로자·원수급인·하수급인의 보험관계와 보수·보험료 산정 기준을 규정해 고용·산재 위험의 적용 대상과 부담 주체를 판단하는 기준이 됩니다.',
    facts: ['보험가입자와 보험관계의 성립·소멸을 규정', '보수·보험료율·월별 보험료·정산·납부기한을 규정', '도급사업의 원수급인·하수급인 구조와 신고 의무를 규정', '법률 제21472호와 제21532호는 시행일이 다른 개정본'],
    affectedTargets: ['사업주·근로자', '원수급인·하수급인', '예술인·노무제공자', '고용·산재보험 운영기관'],
    damageTypes: ['가입 누락', '보험료 산정·체납', '도급 책임 분쟁', '적용 범위 오판'], industries: ['고용보험', '산재보험', '건설·도급', '플랫폼 노동'],
    keywords: ['보험가입자', '보험료 산정', '원수급인', '하수급인', '도급사업'],
    signals: [{ label: '법률번호', value: '제21472호·제21532호', basis: '법령 표제부', tone: 'blue' }, { label: '핵심 기준', value: '가입·산정·징수', basis: '제1장~제3장 조문 체계', tone: 'orange' }, { label: '적용 구조', value: '원·하수급인', basis: '도급사업 관련 조문', tone: 'red' }],
    reviewActions: ['위험 후보의 책임 주체를 보험가입자·원수급인·하수급인 정의와 대조', '보험료 산정 기준과 신고·정산 주기를 상품 운영 프로세스에 반영', '법률번호별 시행일과 개정 조문을 버전별로 연결'], evidenceConfidence: 4.9,
    scores: { novelty: 2.6, growth: 2.8, severity: 3.8, spread: 4.1, coverageGap: 3.5, evidenceConfidence: 4.9 },
  }),
  employment: profile({
    title: '고용보험법', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '고용보험의 적용 범위, 피보험자 관리, 고용안정·직업능력개발, 실업급여의 법적 운영 기준을 정합니다.',
    summary: '고용 형태와 피보험자 자격이 바뀌는 환경에서 누가 고용보험의 적용 대상인지, 어떤 급여와 사업이 연결되는지를 판단하는 기본 법률입니다.',
    facts: ['보험 적용 범위와 적용 제외 대상을 규정', '외국인 근로자·예술인·노무제공자의 적용 조항을 포함', '피보험자격 취득·상실·확인과 신고를 규정', '고용안정·직업능력개발 사업과 실업급여 체계를 규정'],
    affectedTargets: ['근로자·사업주', '예술인·노무제공자', '고용서비스 운영기관', '직업능력개발 사업자'], damageTypes: ['자격 판단 오류', '급여 지급 분쟁', '고용지원 적용 누락'], industries: ['고용보험', '플랫폼 노동', '인력중개', '직업훈련'], keywords: ['피보험자격', '적용 범위', '실업급여', '노무제공자'],
    signals: [{ label: '법률번호', value: '제21372호·제21473호·제21699호', basis: '법령 표제부', tone: 'blue' }, { label: '판단 기준', value: '적용 범위·자격', basis: '제2장 피보험자 관리', tone: 'orange' }, { label: '변화 영역', value: '노무제공자', basis: '제10조의2', tone: 'red' }], reviewActions: ['후보의 고용 형태와 피보험자 자격을 분리해 판단', '적용 제외와 급여 제한 조항을 상품 대상과 대조', '법률번호별 시행일에 맞춰 화면 버전을 구분'], evidenceConfidence: 4.9, scores: { novelty: 2.8, growth: 3.2, severity: 3.6, spread: 4.2, coverageGap: 3.2, evidenceConfidence: 4.9 },
  }),
  health: profile({
    title: '국민건강보험법', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '국민건강보험의 가입자·보험자·보험급여·보험료·요양급여 운영 기준을 정하는 법률입니다.',
    summary: '공적 건강보험의 가입·자격·보험료·급여 구조를 확인해 민영 건강보험의 보장 범위와 중복·공백을 분석하는 기준으로 사용합니다.',
    facts: ['가입자 종류와 사업장 신고·자격 변동을 규정', '국민건강보험공단의 업무와 보험료 부과·징수를 규정', '보험급여와 요양급여비용의 기준을 규정', '제21235호·제21522호·제21687호는 시행일이 다른 개정본'], affectedTargets: ['직장가입자·지역가입자', '의료기관·요양기관', '국민건강보험공단', '민영 건강보험 가입자'], damageTypes: ['자격·보험료 분쟁', '급여 범위 중복', '의료비 부담 전가'], industries: ['건강보험', '의료서비스', '요양·돌봄'], keywords: ['가입자 자격', '보험료', '요양급여', '보험급여'], signals: [{ label: '법률번호', value: '제21235호·제21522호·제21687호', basis: '법령 표제부', tone: 'blue' }, { label: '핵심 기준', value: '가입·보험료·급여', basis: '제2장~제4장 체계', tone: 'orange' }, { label: '연결 분야', value: '민영 건강보험', basis: '공적·민영 보장 관계', tone: 'green' }], reviewActions: ['공적 급여와 민영 보장의 중복·공백을 구분', '가입자 자격과 보험료 부과 기준을 상품 대상과 연결', '시행일별 법률 버전을 상세 화면에서 구분'], evidenceConfidence: 4.9, scores: { novelty: 2.5, growth: 3.4, severity: 3.4, spread: 4.1, coverageGap: 3.0, evidenceConfidence: 4.9 },
  }),
  agriculture: profile({
    title: '농어업재해보험법 및 시행령', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '농작물·가축·어업 관련 재해보험의 대상, 보상 범위, 보험료율, 손해평가와 재보험 운영 기준을 정합니다.',
    summary: '기후·자연재해에 대한 농어업 보험의 보상 대상과 손해평가 체계를 정하는 법령군으로, 재해보험 상품과 재보험 구조를 분석할 때 핵심 기준이 됩니다.',
    facts: ['재해보험의 종류와 보험목적물·보상 범위를 규정', '보험료율 산정과 사고예방의무·손해평가를 규정', '손해평가사 자격과 업무를 규정', '시행령은 보상 재해 범위와 보험가입자 기준을 세부화'], affectedTargets: ['농업인·어업인', '재해보험 사업자', '손해평가인·손해평가사', '재보험기금 운영기관'], damageTypes: ['자연재해 농작물 손해', '가축·어업 손해', '손해평가 분쟁', '재보험기금 부담'], industries: ['농업보험', '어업보험', '기후·자연재해', '재보험'], keywords: ['재해보험', '손해평가', '보험료율', '재보험기금'], signals: [{ label: '법령군', value: '법률·시행령', basis: '농어업재해보험법·시행령', tone: 'blue' }, { label: '핵심 기준', value: '보상 재해·손해평가', basis: '법률 제6조·제11조, 시행령 제8조·제12조', tone: 'orange' }, { label: '기후 연결', value: '자연재해', basis: '보험목적물·보상 범위', tone: 'red' }], reviewActions: ['재해 유형별 보상 범위와 면책 구조를 분리', '손해평가 데이터와 재보험기금 부담을 PML 분석에 반영', '법률과 시행령의 시행일을 함께 표시'], evidenceConfidence: 4.9, scores: { novelty: 3.1, growth: 4.0, severity: 4.2, spread: 3.8, coverageGap: 3.1, evidenceConfidence: 4.9 },
  }),
  insuranceBusiness: profile({
    title: '보험업법 시행령', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '보험종목·허가·보험회사·모집·보험대리점·통신판매·소액단기보험 등 보험업 운영의 세부 요건을 정합니다.',
    summary: '새로운 위험을 상품으로 전환할 때 보험종목 분류, 허가·등록, 모집 방식과 판매 주체의 요건을 확인하는 기본 규제 기준입니다.',
    facts: ['보험상품과 보험종목의 세부 범위를 규정', '보험업 허가와 자본금·기금 요건을 규정', '보험설계사·대리점·중개사의 등록과 영업범위를 규정', '통신판매전문보험회사와 소액단기전문보험회사 규정을 포함'], affectedTargets: ['보험회사', '보험설계사·대리점·중개사', '통신판매 채널', '소액단기보험 사업자'], damageTypes: ['허가·등록 요건 미충족', '모집 방식 위반', '상품종목 분류 오류'], industries: ['보험업', '모집·판매', '디지털보험', '소액단기보험'], keywords: ['보험종목', '허가', '보험모집', '통신판매', '소액단기보험'], signals: [{ label: '법령유형', value: '대통령령', basis: '법령 표제부', tone: 'blue' }, { label: '핵심 기준', value: '허가·모집·종목', basis: '제1장~제4장 체계', tone: 'orange' }, { label: '신사업 연결', value: '소액단기·통신판매', basis: '제13조·제13조의2', tone: 'green' }], reviewActions: ['후보 상품의 보험종목과 허가 요건을 대조', '모집·판매 채널별 등록 요건을 분리', '보험업법 본문과 시행령의 위임 관계를 함께 기록'], evidenceConfidence: 4.9, scores: { novelty: 2.8, growth: 3.3, severity: 3.8, spread: 4.0, coverageGap: 3.1, evidenceConfidence: 4.9 },
  }),
  fisheries: profile({
    title: '어선원 및 어선 재해보상보험법', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '어선원과 어선의 재해보상보험 가입, 보험급여, 재정·운영 기준을 정합니다.', summary: '어선원 재해와 어선 사고에 대한 보상 범위, 보험가입자와 급여 구조를 정하는 특수 보험 법률입니다.', facts: ['어선원재해보상보험의 보험가입자와 보험관계를 규정', '요양·부상·장해·유족·장례비 등 보험급여를 규정', '어선 재해보상보험의 운영·재정·감독 구조를 규정'], affectedTargets: ['어선원', '어선 소유자·사업자', '수산업 보험 운영기관'], damageTypes: ['어선원 업무상 재해', '부상·장해·사망', '어선 사고 손해'], industries: ['어선원 재해보험', '수산업', '해상보험'], keywords: ['어선원 재해', '보험급여', '어선 사업자', '장해급여'], signals: [{ label: '법령번호', value: '제21441호', basis: '법령 표제부', tone: 'blue' }, { label: '보험 범위', value: '요양·장해·유족', basis: '제2절 보험급여', tone: 'red' }], reviewActions: ['어선원·어선 소유자별 보험관계 구분', '재해 유형별 급여와 민영 해상보험의 관계 정리'], evidenceConfidence: 4.9, scores: { novelty: 2.7, growth: 2.9, severity: 4.0, spread: 2.8, coverageGap: 2.7, evidenceConfidence: 4.9 },
  }),
  postal: profile({
    title: '우체국보험특별회계법', source: '국가법령정보센터', topic: '법령·규제', isRegulatory: true,
    event: '우체국보험사업의 특별회계 설치, 적립금 조성·운용과 결산 기준을 정합니다.', summary: '우체국보험사업의 회계와 적립금 운용 구조를 확인하는 법률로, 보험사업의 재정·자본 운용 맥락을 파악하는 자료입니다.', facts: ['우체국보험사업 운영을 위한 특별회계를 설치', '보험료 중 부가보험료와 적립금 조성 구조를 규정', '적립금 운용·대출·결산·예비비를 규정'], affectedTargets: ['우체국보험사업', '과학기술정보통신부·우정사업본부', '우체국보험 가입자'], damageTypes: ['적립금 운용 위험', '회계·결산 관리 위험'], industries: ['생명보험', '공공보험사업', '자산운용'], keywords: ['우체국보험', '특별회계', '적립금', '자산운용'], signals: [{ label: '법률번호', value: '제21651호', basis: '법령 표제부', tone: 'blue' }, { label: '핵심 기준', value: '적립금·회계', basis: '제1조~제10조', tone: 'orange' }], reviewActions: ['보험사업의 회계와 상품 위험을 분리해 분석', '적립금 운용 기준과 자산위험을 연결'], evidenceConfidence: 4.9, scores: { novelty: 2.2, growth: 2.4, severity: 3.1, spread: 2.4, coverageGap: 2.2, evidenceConfidence: 4.9 },
  }),
}

const researchRules: Array<[RegExp, CuratedArticleMetadata]> = [
  [ /2026-07-ils-market-insights-july/i, profile({ title: '2026년 7월 보험연계증권 시장 인사이트', source: 'Swiss Re Capital Markets', topic: '보험연계증권·재보험', publishedAt: '2026.07', event: '2026년 상반기 재해채권 발행이 사상 최대 수준을 기록하며 재해위험 자본시장의 공급이 확대됐습니다.', summary: '2026년 상반기 재해채권 발행액은 176억 달러로 64건의 거래가 이뤄졌고, 미국 풍해 중심의 위험이 자본시장으로 이전되면서 재보험 용량을 보완하고 있습니다.', facts: ['2026년 상반기 재해채권 발행액 176억 달러', '상반기 거래 64건으로 역대 최대 상반기 발행 기록', '신규 스폰서 12곳이 재해채권 시장에 진입', '상반기 발행의 50% 이상이 미국 풍해 위험에 집중', 'Meritage Re 2026-1과 Gateway Re 2026-1 거래에서 다년·다위험 보장 구조가 확인됨'], affectedTargets: ['재보험 수요 기업', '자연재해 고위험 지역 보험자', 'ILS 투자자', '재해위험 자본시장'], damageTypes: ['자연재해 대형손해', '재보험 용량 부족', '위험집중·스프레드 변동'], industries: ['재보험', '재해보험', '자본시장', '주택보험'], keywords: ['ILS', '재해채권', '재보험 용량', '미국 풍해', '대재해위험'], signals: [{ label: '상반기 발행액', value: 'USD 17.6bn', basis: 'Swiss Re Capital Markets Deal Database, 2026.06.30', tone: 'blue' }, { label: '거래 건수', value: '64건', basis: '2026년 상반기 시장 요약', tone: 'green' }, { label: '미국 풍해 비중', value: '50% 이상', basis: '모델 기준 기대손실 구성', tone: 'red' }], reviewActions: ['자연재해 위험의 재보험·ILS 분산 구조를 상품전략에 반영', '미국 풍해 집중도와 누적 PML을 별도로 산정', '재해채권의 트리거·기대손실·스프레드 정보를 위험자본 지표로 분리'], evidenceConfidence: 4.8, scores: { novelty: 4.2, growth: 4.8, severity: 4.5, spread: 4.4, coverageGap: 3.9, evidenceConfidence: 4.8 } }) ],
  [ /Warming Switzerland|sri-2026-06-warming/i, profile({ title: '스위스 폭염과 더워지는 미래', source: 'Swiss Re Institute', topic: '기후·자연재해', publishedAt: '2026.06', event: '스위스의 연간 폭염일수가 증가하면서 건강·노동·도시 인프라에 걸친 복합 위험이 커지고 있습니다.', summary: '폭염은 눈에 보이는 재해보다 늦게 인식되지만 고령자·취약계층의 건강과 노동 생산성, 도시 인프라를 동시에 압박하는 누적 위험입니다.', facts: ['폭염일수가 1990년 연 5일에서 현재 10~15일로 증가', '2003년 유럽 폭염 당시 스위스 사망률 1.5% 증가', '3°C 온난화 시 세기 중반 폭염일수가 연 20~30일까지 증가할 수 있음', '열 위험은 건강·노동·인프라·에너지 수요로 파급'], affectedTargets: ['고령자·취약계층', '야외 노동자', '도시 거주자', '지자체·전력·보건 서비스'], damageTypes: ['열 관련 건강 피해', '노동 생산성 저하', '도시 열섬·인프라 부담', '에너지 수요 증가'], industries: ['건강·상해보험', '고용·산재', '재산보험', '공공 인프라'], keywords: ['폭염', '열 스트레스', '기후 적응', '취약계층', '도시 열섬'], signals: [{ label: '폭염일수', value: '10~15일/년', basis: 'Swiss Re Institute 본문', tone: 'orange' }, { label: '1990년 대비', value: '5일 → 10~15일', basis: '스위스 폭염일수 비교', tone: 'blue' }, { label: '2003년 사망률', value: '+1.5%', basis: '2003년 유럽 폭염 사례', tone: 'red' }], reviewActions: ['폭염 노출과 의료 이용·산재 데이터를 연결', '고령자·야외 노동자 등 취약집단의 보장 구조를 분리', '지역별 폭염 기준과 손해 트리거를 정의'], evidenceConfidence: 4.7, scores: { novelty: 3.8, growth: 4.6, severity: 4.2, spread: 4.6, coverageGap: 3.8, evidenceConfidence: 4.7 } }) ],
  [ /AXA_PR/i, profile({ title: 'AXA 2026년 1분기 보험시장 활동 지표', source: 'AXA Group', topic: '보험시장·자본력', publishedAt: '2026.05', event: 'AXA의 2026년 1분기 손해보험·생명·건강보험 매출이 가격과 물량 효과를 바탕으로 성장했습니다.', summary: 'AXA 활동 지표는 위험 발생률이 아니라 글로벌 보험시장의 수요·가격·자본력 흐름을 보여주는 시장 자료입니다.', facts: ['총 보험료·기타 매출 380억 유로', '전년 대비 6% 성장', 'P&C 215억 유로, Life & Health 165억 유로', 'Solvency II 비율 211%', '2026년 EPS 성장 목표 6~8%'], affectedTargets: ['P&C 보험시장', '기업성 보험', '생명·건강보험', '재보험·자본시장'], damageTypes: ['가격·물량 변화', '금리·인플레이션 영향', '시장 변동성', '재보험 수익성 압력'], industries: ['손해보험', '생명·건강보험', '재보험'], keywords: ['AXA', 'P&C', 'Life & Health', 'Solvency II', '가격 효과'], signals: [{ label: '총 매출', value: '€38.0bn', basis: 'AXA 1Q26 활동 지표', tone: 'blue' }, { label: '전년 대비', value: '+6%', basis: '전년 동기 비교', tone: 'green' }, { label: 'Solvency II', value: '211%', basis: '2026.03.31 기준', tone: 'orange' }], reviewActions: ['시장 성장 지표와 실제 손해 지표를 분리', '가격 효과와 물량 효과를 별도 기록', '자본건전성 지표의 기준일과 변동 원인을 함께 표시'], evidenceConfidence: 4.8, scores: { novelty: 2.8, growth: 4.0, severity: 2.8, spread: 3.5, coverageGap: 2.4, evidenceConfidence: 4.8 } }) ],
  [ /r_f_651_2/i, profile({ title: '생성형 AI와 보험업무의 실제 활용 격차', source: '보험연구원(KIRI)', topic: 'AI·디지털 전환', publishedAt: '2026', event: '보험업무는 AI 활용 잠재력은 높지만 실제 활용은 업무별로 제한돼 법적·검증·시스템 연계 장벽이 나타납니다.', summary: '보험 관련 직업은 AI 잠재노출도와 실제 관측노출도 사이의 차이가 크며, 단순 자동화보다 내부 시스템 연계와 책임·검증 구조가 핵심 과제입니다.', facts: ['보험 관련 직업의 AI 잠재노출도 0.49~0.54', '보험 관련 업무 104개 중 AI 활용 가능 업무 83개', '실제 충분한 AI 활용이 관측된 업무는 8개', '보험설계사의 관측노출도 0.319, 보험계리사의 잠재노출도 0.537'], affectedTargets: ['보험설계사·계리사', '손해사정·언더라이팅 조직', '보험회사 내부 시스템', '고객·업무 책임자'], damageTypes: ['AI 판단 오류', '업무 책임 불명확', '개인정보·기밀정보 노출', '자동화 편향'], industries: ['보험업', 'AI·소프트웨어', '금융사이버', '업무배상책임'], keywords: ['생성형 AI', '잠재노출도', '관측노출도', '업무 자동화', '책임·검증'], signals: [{ label: '잠재노출도', value: '0.49~0.54', basis: '보험 관련 직업 평가', tone: 'blue' }, { label: '가능 업무', value: '83/104개', basis: '전문가 평가 결과', tone: 'green' }, { label: '실제 활용 관측', value: '8개', basis: '실사용 로그 분석', tone: 'orange' }], reviewActions: ['AI 업무별 오류·책임·검증 기준을 분리', '내부 시스템 연계 여부와 접근권한을 인수요소로 정의', '생성물·개인정보·기밀정보 관련 법적 책임을 별도 평가'], evidenceConfidence: 4.6, scores: { novelty: 4.5, growth: 4.4, severity: 3.7, spread: 4.0, coverageGap: 4.1, evidenceConfidence: 4.6 } }) ],
  [ /EU 은행권의 암호자산/i, profile({ title: 'EU 은행권 암호자산 건전성 규제', source: '보험연구원(KIRI)', topic: '금융규제·암호자산', event: 'EBA가 EU 은행의 암호자산 위험노출액과 자기자본요건을 구체화하는 규제기술표준을 발표했습니다.', summary: '암호자산의 위험가중치와 자본요건이 구체화되면서 은행·금융기관의 보유·거래 위험과 관련 책임보험 수요를 함께 살펴볼 수 있습니다.', facts: ['EBA가 암호자산 위험노출액 산정 RTS를 발표', 'CRR 3·MiCAR·바젤 기준을 반영', '자산연계토큰 제2버킷 위험가중치 250%', '암호자산을 위험 수준별 세 개 버킷으로 구분'], affectedTargets: ['은행·금융기관', '암호자산 발행·거래 사업자', '자본시장 투자자', '금융감독기관'], damageTypes: ['자본적정성 악화', '암호자산 가격 변동', '거래·보관 손실', '규제 위반 책임'], industries: ['금융보험', '암호자산', '사이버·금융범죄'], keywords: ['EBA', 'CRR 3', 'MiCAR', '위험가중치', '암호자산'], signals: [{ label: '위험가중치', value: '250%', basis: '자산연계토큰 제2버킷', tone: 'red' }, { label: '규제 기준', value: 'CRR 3·MiCAR', basis: 'EBA RTS 설명', tone: 'blue' }], reviewActions: ['암호자산 보유·거래·수탁별 책임을 구분', '자본요건과 금융기관 보험수요를 연결', 'EU 규제와 국내 적용 가능성을 분리'], evidenceConfidence: 4.5, scores: { novelty: 4.0, growth: 3.8, severity: 4.1, spread: 3.5, coverageGap: 3.9, evidenceConfidence: 4.5 } }) ],
  [ /리튬이온 배터리/i, profile({ title: '리튬이온 배터리 위험과 보험 공백', source: '보험연구원(KIRI)', topic: '배터리·화재위험', event: '리튬이온 배터리 사용이 확대되면서 열폭주·화재·환경오염·공급망 위험이 함께 커지고 있습니다.', summary: '전기차·BESS·전자기기에서 배터리 수요가 빠르게 증가하지만 열폭주와 누적 화재, 폐기·공급망 손해가 기존 보장 구조에 새로운 부담을 줍니다.', facts: ['2024년 LIB 수요 1.3TWh, 전년 대비 31.9% 증가', '2035년 수요 5.6TWh 전망', '전기차용 수요 898GWh, BESS용 307GWh', '열폭주에 따른 화재·폭발과 폐기 과정의 환경위험'], affectedTargets: ['전기차·BESS 운영자', '배터리 제조·보관 시설', '전자기기·의료기기 사업자', '재활용·폐기 사업자'], damageTypes: ['열폭주·화재·폭발', '인접 시설·차량 손해', '환경오염', '공급망·근로자 건강 손해'], industries: ['자동차보험', '재산보험', '배상책임보험', '환경·공급망'], keywords: ['리튬이온 배터리', '열폭주', 'BESS', '전기차', '화재'], signals: [{ label: '2024년 수요', value: '1.3TWh', basis: 'SNE Research 인용', tone: 'blue' }, { label: '2035년 전망', value: '5.6TWh', basis: '본문 시장 전망', tone: 'green' }, { label: '전년 증가율', value: '+31.9%', basis: '2024년 수요 비교', tone: 'red' }], reviewActions: ['배터리 종류·설치 장소·충전 상태별 손해를 분리', '열폭주 확산과 인접 손해의 PML을 따로 산정', '환경오염·공급망·근로자 손해의 책임보험 연결성을 검토'], evidenceConfidence: 4.7, scores: { novelty: 4.4, growth: 4.8, severity: 4.8, spread: 4.4, coverageGap: 4.6, evidenceConfidence: 4.7 } }) ],
  [ /미국, 반려동물보험/i, profile({ title: '미국 반려동물보험 시장 성장', source: '보험연구원(KIRI)', topic: '반려동물·건강보험', event: '미국 반려동물보험 원수보험료와 가입 동물이 빠르게 증가했지만 가입률은 낮아 성장 여지가 남아 있습니다.', summary: '치료비 상승과 반려동물을 가족으로 보는 인식이 수요를 만들고 있으며, 건강관리 서비스·파트너십·인수 전략이 상품 경쟁 요소로 부상했습니다.', facts: ['미국 원수보험료가 2019년 15.6억 달러에서 2023년 39.1억 달러로 증가', '보험 가입 개·고양이가 2019년 252만 마리에서 2023년 568만 마리로 증가', '미국 반려동물보험 가입률은 4% 미만', '2024~2030년 시장 성장률 17.5% 전망'], affectedTargets: ['반려동물 보호자', '동물병원·펫케어 사업자', '반려동물보험 사업자'], damageTypes: ['진료비 상승', '만성질환·고액치료', '도덕적 해이·역선택', '동물병원 비용 변동'], industries: ['반려동물보험', '건강관리', '동물의료'], keywords: ['반려동물보험', '원수보험료', '가입률', '동물병원', '펫케어'], signals: [{ label: '2023년 원수보험료', value: '39.1억 달러', basis: 'NAPHIA 2024 인용', tone: 'blue' }, { label: '2019~2023 CAGR', value: '25.9%', basis: '본문 계산', tone: 'green' }, { label: '가입률', value: '4% 미만', basis: '본문 시장 평가', tone: 'orange' }], reviewActions: ['반려동물 종·연령·질환별 손해율을 분리', '진료비 데이터와 보장한도를 연결', '건강관리 서비스 결합 시 도덕적 해이와 역선택을 구분'], evidenceConfidence: 4.6, scores: { novelty: 3.8, growth: 4.7, severity: 3.5, spread: 3.6, coverageGap: 4.1, evidenceConfidence: 4.6 } }) ],
  [ /바이러스 보험/i, profile({ title: '대재해채권을 통한 전염병 위험 이전', source: '보험연구원(KIRI)', topic: '전염병·재보험', event: '전염병 대규모 발생에 대비해 대재해채권과 긴급대응기금을 활용하는 위험 이전 구조가 제시됐습니다.', summary: '전염병은 확산 속도와 지역·규모를 예측하기 어려워 초기 자금 공급이 중요하며, 재보험과 자본시장 연계가 대응 수단이 됩니다.', facts: ['전염병 긴급대응기금 규모 5억 달러', '보장 대상으로 신종 인플루엔자·SARS·MERS·에볼라를 제시', '연간 보험료 5,500만~6,500만 달러 수준 전망', '발생 정도와 전염 규모에 따라 보상금액을 결정하는 구조'], affectedTargets: ['정부·국제기구', '재보험사', '보건·의료기관', '감염병 고위험 사업자'], damageTypes: ['대규모 감염·사망', '영업중단', '의료비·방역비', '초기 대응 자금 부족'], industries: ['재보험', '전염병보험', '건강보험', '공공재난금융'], keywords: ['전염병', '대재해채권', '긴급대응기금', '팬데믹', '재보험'], signals: [{ label: '기금 규모', value: '5억 달러', basis: 'World Bank PEF 자료 인용', tone: 'blue' }, { label: '연간 보험료', value: '5,500만~6,500만 달러', basis: '본문 전망', tone: 'orange' }], reviewActions: ['트리거 기준과 보상금액 산정 방식을 분리', '감염병 확산·영업중단·방역비의 누적 PML을 산정', '공공기금과 민간보험의 역할을 구분'], evidenceConfidence: 4.4, scores: { novelty: 3.7, growth: 3.8, severity: 4.9, spread: 4.9, coverageGap: 4.5, evidenceConfidence: 4.4 } }) ],
  [ /사이버 위험 보험/i, profile({ title: '사이버보험과 사이버 대재해채권', source: '보험연구원(KIRI)', topic: '사이버·정보보호', event: '사이버 범죄 비용과 랜섬웨어 활동이 증가하면서 사이버보험과 보험연계증권 활용이 확대되고 있습니다.', summary: '사이버 위험은 빈도·규모·정교함이 동시에 커지고 재보험 자본의 한계가 나타나 보험연계증권을 통한 위험 분산이 대안으로 제시됩니다.', facts: ['사이버 범죄 피해 비용은 2015년 3조 달러에서 2025년 10.5조 달러 전망', '2023년 3분기 랜섬웨어 활동이 전년 동기 대비 95% 증가', '세계 사이버보험 원수보험료가 2017년 40억 달러에서 2022년 130억 달러로 증가', '2023년 영국 Beazley가 4,500만 달러 규모 사이버 대재해채권 발행'], affectedTargets: ['기업·기관', '개인정보·데이터 보유자', '클라우드·IT 사업자', '사이버보험·재보험사'], damageTypes: ['랜섬웨어·해킹', '개인정보 유출', '영업중단', '복구·통지·법률비용'], industries: ['사이버보험', '기업성보험', 'IT·클라우드', '재보험'], keywords: ['사이버보험', '랜섬웨어', '사이버 대재해채권', 'ILS', '개인정보'], signals: [{ label: '2025년 피해 비용 전망', value: '10.5조 달러', basis: '본문 인용 자료', tone: 'red' }, { label: '랜섬웨어 증가', value: '+95%', basis: '2023년 3분기 비교', tone: 'orange' }, { label: '사이버보험 시장', value: '2022년 130억 달러', basis: '본문 시장 규모', tone: 'blue' }], reviewActions: ['사이버 사고 유형별 직접손해·간접손해 구분', '보안 수준과 면책·자기부담금 구조를 연결', '집중위험과 대재해채권 트리거를 별도 설계'], evidenceConfidence: 4.6, scores: { novelty: 4.0, growth: 4.7, severity: 4.5, spread: 4.8, coverageGap: 4.5, evidenceConfidence: 4.6 } }) ],
  [ /일본 생명보험/i, profile({ title: '일본 생명보험사의 헬스케어 확장', source: '보험연구원(KIRI)', topic: '생명보험·헬스케어', event: '일본 생명보험사가 금리·인구구조 변화에 대응해 변액보험과 간병·헬스케어 등 비보험 영역을 확대하고 있습니다.', summary: '금리 정상화와 고령화로 자산형성·간병·건강관리 수요가 커지며 생명보험사의 상품과 서비스 결합이 강화되는 사례입니다.', facts: ['일본은행이 2024년 3월 17년 만에 금리 인상', '공적보험 외 헬스케어산업 시장이 2020년 18.5조 엔에서 2050년 59.9조 엔 전망', '일본 대형 생명보험사가 헬스케어·요양·보육 기업과 제휴·인수 추진', '변액보험과 비보험 서비스 확장이 주요 전략으로 제시됨'], affectedTargets: ['고령자·간병 수요자', '생명보험 가입자', '헬스케어·요양 서비스 사업자', '생명보험사'], damageTypes: ['장수·간병 비용', '금리·자산운용 변동', '건강관리 서비스 책임'], industries: ['생명보험', '간병·요양', '헬스케어', '자산운용'], keywords: ['일본 생명보험', '간병', '헬스케어', '변액보험', '금리 정상화'], signals: [{ label: '헬스케어 시장', value: '18.5조 → 59.9조 엔', basis: '일본 경제산업성 전망', tone: 'green' }, { label: '금리 변화', value: '17년 만의 금리 인상', basis: '2024년 일본은행 정책', tone: 'blue' }], reviewActions: ['보장상품과 헬스케어 서비스의 책임을 분리', '간병·장수 위험과 자산운용 위험을 별도 평가', '국내 인구구조·의료체계와 직접 비교하지 않고 사례로 활용'], evidenceConfidence: 4.4, scores: { novelty: 3.6, growth: 4.2, severity: 3.8, spread: 3.5, coverageGap: 3.7, evidenceConfidence: 4.4 } }) ],
  [ /자동차보험자동차보험/i, profile({ title: '미국 자동차보험 의무가입 예외와 책임 구조', source: '보험연구원(KIRI)', topic: '자동차보험·책임', event: '미국 대부분 주가 자동차보험을 의무화하지만 뉴햄프셔와 버지니아는 재정능력 증빙 또는 수수료 방식의 예외를 둡니다.', summary: '자동차보험 가입 의무와 무보험 운전자의 재정책임을 비교해 의무보험·책임보험 설계의 차이를 보여주는 자료입니다.', facts: ['2023년 기준 뉴햄프셔·버지니아를 제외한 미국 대부분 주에서 자동차보험 의무', '뉴햄프셔는 신체·재산 손해에 대한 재정능력 증빙을 요구', '버지니아는 무보험 운전 수수료를 선택지로 허용', '주별 보장 범위·금액 규정이 상이'], affectedTargets: ['자동차 소유자·운전자', '피해자', '자동차보험자', '주 정부·보험감독기관'], damageTypes: ['대인·대물 사고', '무보험 손해', '책임 범위 분쟁'], industries: ['자동차보험', '모빌리티', '배상책임보험'], keywords: ['자동차보험 의무', '무보험 운전', '재정능력 증빙', '대인·대물'], signals: [{ label: '의무가입 예외', value: '2개 주', basis: '미국 주별 제도 비교', tone: 'orange' }, { label: '재정능력 기준', value: '총 10만 달러', basis: '뉴햄프셔 안내자료 인용', tone: 'blue' }], reviewActions: ['의무보험과 재정책임 대체 구조를 구분', '대인·대물 최소한도와 무보험 손해를 분리'], evidenceConfidence: 4.2, scores: { novelty: 2.9, growth: 2.8, severity: 3.9, spread: 3.1, coverageGap: 3.3, evidenceConfidence: 4.2 } }) ],
  [ /재산보험/i, profile({ title: '플로리다 주택보험 시장 위기', source: '보험연구원(KIRI)', topic: '재산보험·자연재해', event: '플로리다의 허리케인 노출, 보험사기·소송비용과 재보험 이탈이 주택보험 시장을 압박했습니다.', summary: '자연재해 위험만이 아니라 보험사기와 소송비용, 지역보험사의 자본력 부족이 재산보험 시장의 보장 가능성과 보험료에 함께 영향을 줍니다.', facts: ['플로리다 주민 2,150만 명 중 약 75%가 해안 카운티에 거주', 'Citizens 보험계약이 2020년 47만 4,630건에서 2022년 93만 1,357건으로 96.2% 증가', '손실 이후 보험료 증가율이 플로리다에서 최대 50% 수준', '보험사기와 높은 소송비용이 시장 위기의 주요 요인으로 제시'], affectedTargets: ['해안 지역 주택 소유자', '지역 주택보험사', '재보험사·공영보험자', '주택 수리업체·법률서비스'], damageTypes: ['허리케인·홍수 손해', '보험사기', '소송비용', '재보험 용량 부족'], industries: ['주택보험', '재산보험', '재보험', '재난보험'], keywords: ['플로리다 주택보험', '허리케인', '보험사기', '소송비용', '재보험'], signals: [{ label: '해안 거주 비중', value: '약 75%', basis: '미국 인구조사국 인용', tone: 'red' }, { label: 'Citizens 계약 증가', value: '+96.2%', basis: '2020~2022년 비교', tone: 'orange' }, { label: '보험료 증가율', value: '최대 50%', basis: '손실 이후 갱신 비교', tone: 'blue' }], reviewActions: ['자연재해·사기·소송비용을 손해 원인별로 분리', '지역집중도와 재보험 회수 가능성을 PML에 반영', '보험료 상승과 보장 축소의 시장 영향을 구분'], evidenceConfidence: 4.5, scores: { novelty: 3.5, growth: 4.0, severity: 4.8, spread: 4.4, coverageGap: 4.6, evidenceConfidence: 4.5 } }) ],
  [ /테러위험/i, profile({ title: '테러 위험의 유형 변화와 보험시장', source: '보험연구원(KIRI)', topic: '테러·정치폭력', event: '테러 위험이 특정 조직의 계획 공격에서 소프트 타깃·사이버 공격 등으로 다양화되고 있습니다.', summary: '테러는 발생 빈도 예측이 어렵고 손실 규모가 커 정부기금과 민간보험의 결합이 필요한 대표적 누적·대형손실 위험입니다.', facts: ['2017년 전 세계 테러 공격 건수 2만 2,500건', '민간인 대상 공격과 사이버 공격 위협이 증가', '자동차·휴대용 무기를 이용한 대량 살상 공격 유형이 확대', '주요국은 정부 기금으로 민간 테러보험 시장을 지원'], affectedTargets: ['기업·시설 운영자', '소프트 타깃 시설', '정부·공공기관', '테러보험·재보험사'], damageTypes: ['인명·재산 대형손해', '영업중단', '사이버 공격', '정치폭력·전쟁 연계 손해'], industries: ['테러보험', '재산보험', '기업휴지보험', '사이버보험'], keywords: ['테러보험', '소프트 타깃', '사이버 공격', '정부기금', '대형손실'], signals: [{ label: '2017년 공격 건수', value: '22,500건', basis: 'Global Terrorism Index 인용', tone: 'red' }, { label: '시장 구조', value: '민간보험·정부기금', basis: '주요국 테러보험 제도', tone: 'blue' }], reviewActions: ['테러·전쟁·사이버 위험의 약관상 구분', '정부기금과 민간보험의 손실분담 구조 분석', '소프트 타깃 시설의 집중 PML 산정'], evidenceConfidence: 4.1, scores: { novelty: 3.6, growth: 3.5, severity: 4.9, spread: 4.6, coverageGap: 4.4, evidenceConfidence: 4.1 } }) ],
  [ /프랑스의 건강보험/i, profile({ title: '프랑스 건강보험 재정개선 사례', source: '보험연구원(KIRI)', topic: '건강보험·제도개선', event: '프랑스가 건강보험 재정적자와 지출목표 초과에 대응해 공보험 지출관리와 보완형 건강보험의 역할을 조정하고 있습니다.', summary: '공보험 재정 지속가능성을 위해 지출관리·본인부담·보완형 건강보험·예방을 함께 조정하는 제도개선 사례입니다.', facts: ['2025년 프랑스 사회보장 적자 216억 유로', '사회보장 적자 중 건강보험 부문이 약 74%', '2025년 6월 건강보험지출목표 초과 경보 발동', '단기 지출관리와 중장기 예방·의료접근성 개선을 병행'], affectedTargets: ['공보험 가입자', '의료기관·보험자', '보완형 건강보험 가입자', '프랑스 정부·건강보험공단'], damageTypes: ['의료비 증가', '공보험 재정적자', '본인부담 증가', '보완보험 역할 변화'], industries: ['건강보험', '의료서비스', '보완형 보험', '공공재정'], keywords: ['프랑스 건강보험', 'ONDAM', '건강보험 재정', '본인부담', '보완형 건강보험'], signals: [{ label: '2025년 적자', value: '216억 유로', basis: '프랑스 사회보장국 자료 인용', tone: 'red' }, { label: '건강보험 비중', value: '약 74%', basis: '사회보장 적자 구성', tone: 'orange' }, { label: '지출 경보', value: '2007년 이후 18년 만', basis: 'ONDAM 경보위원회 의견', tone: 'blue' }], reviewActions: ['공보험 급여와 보완형 보험의 역할을 구분', '의료비 증가와 본인부담 변화를 상품 수요와 연결', '해외 제도 사례를 국내 제도에 직접 대입하지 않고 비교자료로 관리'], evidenceConfidence: 4.5, scores: { novelty: 3.5, growth: 3.8, severity: 3.8, spread: 3.4, coverageGap: 3.6, evidenceConfidence: 4.5 } }) ],
  [ /보험개발원_신기술/i, profile({ title: '우주산업 상업화와 우주보험 대응', source: '보험개발원', topic: '우주·신기술', event: '위성 발사가 민간 중심의 반복적·상업적 서비스로 전환되며 우주보험의 데이터·평가 인프라 필요성이 커지고 있습니다.', summary: '우주산업은 반복 발사와 위성 운용으로 보험 수요가 커지지만 국내는 사고 데이터·표준 위험평가·전문인력과 재보험 기반이 부족합니다.', facts: ['위성 발사가 민간 중심의 반복·상업 서비스로 전환', '국내는 사고 데이터와 표준 위험평가 기준이 부족', '일본은 JAXA와 보험사 협력으로 정량평가 체계를 축적', '국내 시장에는 법제·약관·전문인력·정부지원 기반이 과제로 제시'], affectedTargets: ['발사체·위성 사업자', '위성통신·우주서비스 이용자', '보험·재보험사', '정부·연구기관'], damageTypes: ['발사 실패', '위성 운용 손실', '궤도·통신 중단', '재보험 의존'], industries: ['우주보험', '위성통신', '항공·방산', '특종보험'], keywords: ['우주보험', '위성 발사', 'JAXA', '위험평가', '재보험'], signals: [{ label: '산업 변화', value: '민간·반복 발사', basis: '보험개발원 테마동향', tone: 'blue' }, { label: '국내 기반', value: '데이터·기준 부족', basis: '본문 산업 진단', tone: 'red' }, { label: '해외 사례', value: 'JAXA 협력', basis: '일본 우주보험 사례', tone: 'green' }], reviewActions: ['발사·운용 단계별 손해를 분리', '국내외 사고 데이터와 재보험 조건을 연결', '표준 위험평가와 전문인력 수준을 상품화 조건으로 기록'], evidenceConfidence: 4.3, scores: { novelty: 4.6, growth: 4.2, severity: 4.3, spread: 3.5, coverageGap: 4.5, evidenceConfidence: 4.3 } }) ],
  [ /AI_데이터센터|AI_데이터센터|AI.*데이터센터/i, profile({ title: 'AI 데이터센터 건설 확대와 보장 공백', source: '보험연구원(KIRI)', topic: 'AI 인프라·재산보험', event: 'AI 데이터센터의 설비투자와 건설 규모가 확대되면서 기존 보험시장의 보장 용량과 신규 설비 위험이 충돌하고 있습니다.', summary: 'AI 데이터센터는 대규모 자산 집중과 리튬이온 배터리·냉각설비·드론 공격 위험이 결합돼 건설보험과 운영보험 사이의 보장 공백을 키웁니다.', facts: ['2026년 5대 빅테크 데이터센터 설비투자 6,000억 달러 초과', '물리 인프라 투자 약 4,500억 달러', '데이터센터 보험료가 2026년 106억 달러에서 2030년 242억 달러로 성장 전망', '대형 데이터센터 건설단계 보험가액 100~300억 달러', 'AI 전용 설계의 랙 내 리튬이온 배터리와 냉각설비가 화재·수해 위험을 확대'], affectedTargets: ['데이터센터 소유·운영자', '서버·GPU·배터리·냉각설비 사업자', '건설사·대주단', '재산보험·재보험사'], damageTypes: ['대형 화재·열폭주', '냉각액 누출·수해', '건설 지연·영업중단', '드론·지정학적 공격'], industries: ['재산보험', '건설보험', '기업휴지보험', '사이버·테러보험'], keywords: ['AI 데이터센터', '보장 공백', '열폭주', '냉각설비', '누적 PML'], signals: [{ label: '설비투자', value: '6,000억 달러+', basis: 'Swiss Re·KIRI 본문', tone: 'blue' }, { label: '보험료 전망', value: '106억 → 242억 달러', basis: '2026~2030년 전망', tone: 'green' }, { label: '건설단계 보험가액', value: '100~300억 달러', basis: 'S&P Global 인용', tone: 'red' }], reviewActions: ['배터리·냉각설비의 설계와 안전기준을 인수 조건으로 분리', '건설보험과 운영보험의 시운전·영업중단 공백을 구분', '대규모 자산 집중과 드론·전쟁 위험의 PML을 별도 산정'], evidenceConfidence: 4.7, scores: { novelty: 4.7, growth: 4.8, severity: 4.9, spread: 4.4, coverageGap: 4.9, evidenceConfidence: 4.7 } }) ],
]

export function getArticleMetadata(fileName: string): CuratedArticleMetadata | undefined {
  if (/고용보험 및 산업재해보상보험의 보험료징수|고용보험_및_산업재해보상보험의_보험료징수|law74/i.test(fileName)) return laws.employmentCollection
  if (/고용보험법/i.test(fileName)) return laws.employment
  if (/국민건강보험법/i.test(fileName)) return laws.health
  if (/농어업재해보험법/i.test(fileName)) return laws.agriculture
  if (/보험업법 시행령/i.test(fileName)) return laws.insuranceBusiness
  if (/어선원 및 어선 재해보상보험법/i.test(fileName)) return laws.fisheries
  if (/우체국보험특별회계법/i.test(fileName)) return laws.postal
  return researchRules.find(([match]) => match.test(fileName))?.[1]
}
