export type RiskDetailRow = [string, string, string]

export type RiskDetailNarrative = {
  overview: string
  analysisIntro: string
  background: string
  mechanism: string
  damage: string
  exposure: string
  responsibility: string
  management: string
  customerImpact: string
  existingInsurance: string
  additionalInsurance: string
  productIssue: string
  incident: string
  escalation: string
  insuranceBoundary: string
  insuranceReasons: Array<[string, string, string]>
  lossRows: RiskDetailRow[]
  stakeholders: Array<[string, string]>
  coverageRows: RiskDetailRow[]
  questions: string[]
  analysisSections: Array<[string, string]>
  priorityCover: string
  underwriting: string
  evidenceNeeded: string
}

type NarrativeSeed = Omit<RiskDetailNarrative, 'analysisIntro' | 'insuranceReasons' | 'lossRows' | 'stakeholders' | 'coverageRows' | 'questions' | 'analysisSections' | 'priorityCover' | 'underwriting' | 'evidenceNeeded'> & {
  responsibility: string
  management: string
  customerImpact: string
  existingInsurance: string
  additionalInsurance: string
  evidenceNeeded: string
}

const seed = (value: NarrativeSeed & { evidenceNeeded?: string }): RiskDetailNarrative => {
  const evidenceNeeded = value.evidenceNeeded ?? '국내 사고 빈도·평균 손해액·기업별 통제 수준을 확인할 수 있는 원문 자료'
  return {
    ...value,
    analysisIntro: `${value.overview}을 보험의 관점에서 바라볼 때 가장 먼저 구분해야 할 것은, 이 위험이 단순히 하나의 사고나 분쟁으로 끝나는 문제가 아니라는 점입니다. 위험은 ${value.background}에서 시작해 ${value.mechanism}을 거쳐 ${value.incident} ${value.escalation}으로 이어지는 전 과정에서 발생합니다.`,
    evidenceNeeded,
    insuranceReasons: [
      ['손해가 여러 경로로 확대될 수 있음', `${value.incident}은 직접 손해뿐 아니라 복구·분쟁·업무중단 비용으로 이어질 수 있습니다.`, '손해 항목별 보장 구조를 분리해 검토해야 합니다.'],
      ['책임 확정 전 비용이 발생할 수 있음', `${value.damage}에 대한 조사·자문·피해 대응 비용은 최종 책임 판단 전에 먼저 발생할 수 있습니다.`, '방어비용과 배상책임의 보장 경계를 확인해야 합니다.'],
      ['기존 보험과의 경계가 불명확함', value.insuranceBoundary, '기존 약관·특약의 적용 가능성과 공백을 함께 확인합니다.'],
    ],
    lossRows: [
      ['직접 손해·사고', value.damage, '사고 손해'],
      ['법률·방어 비용', `${value.incident} 이후 원인 조사, 전문가 자문, 민원·분쟁 대응 비용이 발생할 수 있습니다.`, '비용 손해'],
      ['복구·재작업 비용', `${value.mechanism}을 중단·복구·재발 방지하는 과정에서 교체, 재처리 또는 정상화 비용이 발생할 수 있습니다.`, '운영 손해'],
      ['계약상 배상책임', `${value.responsibility} 사이의 계약·법률상 책임 분담에 따라 제3자 배상책임으로 확산될 수 있습니다.`, '계약 책임'],
      ['서비스·업무 중단', `${value.escalation}이 장기화되면 매출 손실, 납품 지연, 고객 대응 비용이 추가될 수 있습니다.`, '간접 손해'],
    ],
    stakeholders: [
      ['주요 노출 대상', value.exposure],
      ['위험을 관리하는 주체', value.management],
      ['사고를 경험하는 주체', value.customerImpact],
      ['계약·인수 관계자', `${value.responsibility}의 계약 구조와 책임 분담을 확인해야 보험계약자·피보험자·제3자의 범위를 구분할 수 있습니다.`],
      ['규제·감독 기관', '관련 법령·기술 기준·감독 지침의 변경이 사고 정의와 보장 범위에 영향을 줄 수 있습니다.'],
      ['보험 계약자', '통제 수준, 사고 이력, 로그 보유 여부에 따라 인수조건·면책·자기부담금 검토가 필요합니다.'],
    ],
    coverageRows: [
      ['기존 배상책임보험', value.existingInsurance, '약관 확인'],
      ['재산·운영손해보험', `${value.damage}와 복구·영업중단 비용이 어떤 사고 원인과 조건에서 연결되는지 확인합니다.`, '보장 경계 검토'],
      ['전문·사이버 위험보험', value.additionalInsurance, '연결 가능성 검토'],
      ['법률비용·방어비용', '책임이 확정되기 전 조사·자문·소송·피해 통지 비용을 별도 담보로 구조화할 수 있는지 살펴봅니다.', '구조화 가능'],
      ['신규 특약·시범상품', `${value.productIssue}가 객관적인 사고 정의와 자료로 측정되는 범위부터 제한적 특약을 검토합니다.`, '추가 검토'],
    ],
    questions: [
      `${value.overview}에서 보험사고로 정의할 수 있는 객관적 사건과 발생 시점은 무엇인가?`,
      '직접 손해·방어비용·복구비용·업무중단 손해 중 어디까지 보장할 것인가?',
      `${value.responsibility}의 책임을 어떤 로그·계약·점검 기록으로 구분할 것인가?`,
      `${value.management}의 사전 통제 수준을 인수조건 또는 보험료 조정 요소로 활용할 수 있는가?`,
      `${evidenceNeeded}를 확보했는가?`,
    ],
    analysisSections: [
      ['위험은 특정 결과가 아니라 전 과정에서 만들어진다', `${value.background} ${value.mechanism} 위험은 단일 사건만이 아니라 노출 확대·위험 요인·사고 발생·손해 확산의 과정에서 보험 검토 대상이 됩니다.`],
      ['현재 기준은 결론보다 사건별 판단을 요구한다', `${value.insuranceBoundary} 동일한 위험이라도 발생 원인, 이용 목적, 통제 수준과 계약 구조에 따라 책임과 보장 가능성이 달라질 수 있습니다. 따라서 공식 원문과 실제 사건 기록을 함께 확인해야 합니다.`],
      ['책임 확정 전에도 손해가 발생한다', `${value.damage}와 관련된 조사·복구·분쟁 대응 비용은 최종 책임 판단 전에도 발생할 수 있습니다. 특히 ${value.escalation}`],
      ['책임 주체가 여러 단계로 나뉜다', `${value.responsibility} 사이의 역할과 증빙이 분리되지 않으면 사고 원인과 구상 관계를 확정하기 어렵습니다. ${value.management}의 점검·로그·승인 기록이 책임 판단의 출발점이 됩니다.`],
      ['국내 공식 자료와 손해자료를 함께 봐야 한다', `${evidenceNeeded}는 공개 정책자료만으로 확정할 수 없습니다. 법령·감독 기준·공공 통계는 위험의 존재와 관리 방향을 보여주며, 사고 빈도·손해액·보험 청구자료는 별도로 축적해야 합니다.`],
      ['기존 보험은 일부 손해와 먼저 연결된다', `${value.existingInsurance} ${value.additionalInsurance} 전면적인 신규 담보를 단정하기보다 기존 배상·재산·전문·사이버·법률비용 담보의 적용 범위와 면책을 먼저 대조할 필요가 있습니다.`],
      ['상품화는 사고 정의와 통제 조건을 좁히는 데서 시작한다', `${value.productIssue} 보장 대상을 명확한 사고 시점과 손해 항목으로 제한하고, ${value.management}을 인수조건·자기부담금·면책 기준에 반영할 수 있는지 검토해야 합니다.`],
      ['현실적인 도입은 제한적 특약과 시범상품부터다', `우선 검토 담보는 직접 손해·방어비용·제한적 제3자 배상책임으로 나누어 설계할 수 있습니다. 다만 ${evidenceNeeded}를 확인하고, 실제 약관·법무·계리 검증을 거쳐 보장 범위를 단계적으로 확대해야 합니다.`],
    ],
    priorityCover: '직접 손해·방어비용·제한적 제3자 배상책임',
    underwriting: '사전 점검·관리 로그·책임 증빙·사고 대응 체계',
  }
}

const detailNarratives: Record<string, RiskDetailNarrative> = {
  'ev-battery-fire': seed({
    overview: '전기차 배터리 화재',
    background: '전기차 보급과 고밀도 지하주차장 이용이 함께 늘고 있습니다.',
    mechanism: '배터리 셀 결함·충격·충전 상태가 열폭주와 재발화로 이어지는 구조',
    damage: '차량 전소·주차장 구조물 손상·연기와 소화수로 인한 인접 차량 피해',
    exposure: '전기차 제조사·배터리 제조사·충전사업자·주차장 운영자·차량 소유자',
    productIssue: '배터리 원인과 충전·주차장 관리 원인을 구분하고 재발화 손해를 측정하는 것',
    incident: '배터리 열폭주가 발생해 차량과 주차장 설비에 화재 손해가 발생하면',
    escalation: '소방·대피·전기설비 차단과 장기 주차장 폐쇄가 이어지면',
    insuranceBoundary: '자동차 자기차량손해, 제조물책임, 시설소유자배상책임, 재산·영업중단 담보가 사고 원인별로 나뉘는지 확인합니다.',
    responsibility: '배터리·차량 제조사, 충전사업자, 주차장 운영자, 차량 소유자',
    management: '제조사·충전사업자·주차장 운영자가 BMS·충전기·소방·대피 통제를 운영합니다.',
    customerImpact: '차량 소유자, 주차장 이용자, 인접 점포·건물 소유자가 직접·간접 피해를 받을 수 있습니다.',
    existingInsurance: '차량 손해는 자동차보험, 시설·제3자 손해는 배상책임보험에 연결될 수 있으나 배터리 결함·재발화·집적 손해의 경계를 확인해야 합니다.',
    additionalInsurance: '배터리 제조물책임과 충전·주차장 운영자의 시설배상책임 사이 공백을 확인합니다.',
    evidenceNeeded: '배터리 화재 원인, 재발화율, 지하주차장 손해액과 차량·시설별 분담 자료',
  }),
  'commercial-drone': seed({
    overview: '상업용 드론 배송 사고',
    background: '배송·점검·촬영 등 상업용 드론 운항이 도심과 물류 현장으로 확대되고 있습니다.',
    mechanism: '비행계획·통신·배터리·기상·조종·자동회피 중 하나가 실패해 비행체가 통제 범위를 벗어나는 구조',
    damage: '추락으로 인한 보행자 상해, 차량·건물 파손, 배송물 멸실',
    exposure: '드론 배송사업자·운항자·제조사·정비업체·배송 의뢰 기업',
    productIssue: '운항 로그와 정비 이력으로 운영자 과실·제품 결함·불가항력을 구분하는 것',
    incident: '드론이 통신 두절·배터리 이상·기상 악화로 추락하면',
    escalation: '운항 중단과 조사로 배송 지연·대체 운송·다수 제3자 피해가 생기면',
    insuranceBoundary: '항공·드론 배상책임, 제조물책임, 적재물·운송 손해가 운항 단계별로 연결되는지 확인합니다.',
    responsibility: '운항사업자, 원격조종자, 드론 제조사, 정비업체, 배송 의뢰인',
    management: '운항사업자가 비행 승인·기상 확인·배터리 점검·비상 회항 절차를 관리합니다.',
    customerImpact: '보행자·차량·건물 소유자와 배송물 수령인이 피해를 경험할 수 있습니다.',
    existingInsurance: '드론 배상책임과 운송·적재물 담보가 일부 연결될 수 있으나 자동운항·관제·지상 제3자 손해를 구분해야 합니다.',
    additionalInsurance: '운항 중단·관제 오류·전문서비스 책임과 제조물책임의 연결 가능성을 확인합니다.',
    evidenceNeeded: '비행시간 대비 사고율, 운항 로그 표준, 제3자 손해액과 의무보험 한도 자료',
  }),
  'autonomous-level4': seed({
    overview: '자율주행 Level 4 사고',
    background: '운전자 개입이 제한되거나 없는 자율주행 실증과 상용 서비스가 확대되고 있습니다.',
    mechanism: '센서·지도·판단 소프트웨어·통신·원격관제의 결합 오류가 사고와 책임 공백으로 이어지는 구조',
    damage: '충돌로 인한 인명·차량 손해와 사고 분석·리콜·서비스 중단 비용',
    exposure: '차량 제조사·자율주행 소프트웨어 개발사·운영자·원격관제자·탑승자',
    productIssue: '운전자 과실이 줄어든 환경에서 시스템 결함·운영자 관리·도로 환경의 책임을 분리하는 것',
    incident: '자율주행 시스템이 위험을 감지·판단·회피하지 못해 충돌하면',
    escalation: '사고 데이터 보존·리콜·운행 중단·다수 차량 업데이트가 필요해지면',
    insuranceBoundary: '자동차 배상책임과 제조물책임을 기본으로 하되 소프트웨어 오류·리콜·운영 중단의 담보 경계를 확인합니다.',
    responsibility: '차량 제조사, 소프트웨어 개발사, 운행사업자, 원격관제자, 도로 관리기관',
    management: '운영자와 제조사가 버전관리·센서 점검·원격관제·사고 데이터 보존을 관리합니다.',
    customerImpact: '탑승자·보행자·다른 차량 운전자와 차량 소유자가 피해를 받을 수 있습니다.',
    existingInsurance: '자동차보험의 대인·대물 책임은 연결 가능성이 있으나 시스템 결함·리콜·소프트웨어 책임은 별도 검토가 필요합니다.',
    additionalInsurance: '제품·전문직업·사이버 위험이 자율주행 데이터와 소프트웨어 책임에 어떻게 연결되는지 확인합니다.',
    evidenceNeeded: '주행거리 대비 사고율, 시스템 버전별 사고 기록, 책임 판정과 손해액 자료',
  }),
  'deepfake-phishing': seed({
    overview: '딥페이크 기반 피싱',
    background: '음성·영상 합성 기술이 고도화되면서 지인·임직원 사칭의 신뢰 형성이 쉬워지고 있습니다.',
    mechanism: '공개된 얼굴·음성 정보를 수집해 합성한 뒤 긴급 송금·인증·정보 제공을 유도하는 구조',
    damage: '피해자의 송금액, 계정 탈취, 기업의 지급 승인 오류와 조사 비용',
    exposure: '개인·가족·금융기관·기업의 재무담당자·고객센터',
    productIssue: '피해자 과실, 금융기관 인증 절차, 플랫폼·통신사의 방지조치 책임을 구분하는 것',
    incident: '합성 음성·영상이 가족이나 임직원의 요청처럼 전달되어 송금이 실행되면',
    escalation: '계정 탈취와 추가 피해자 발생, 신고·거래정지·복구 절차가 이어지면',
    insuranceBoundary: '전자금융거래·사이버·신원도용 관련 담보가 사칭 방식과 인증 절차에 따라 적용되는지 확인합니다.',
    responsibility: '사기범, 피해자, 금융기관, 플랫폼·통신사업자, 기업의 승인권자',
    management: '금융기관·기업이 다중 인증·거래 지연·이상 징후 탐지와 임직원 확인 절차를 운영합니다.',
    customerImpact: '개인 피해자와 사칭된 임직원·가족, 자금이 이체된 기업이 손해를 부담할 수 있습니다.',
    existingInsurance: '금융사기·전자금융 관련 담보가 있을 수 있으나 사회공학적 사칭과 피해자 고의·중과실 면책을 확인해야 합니다.',
    additionalInsurance: '사이버보험·신원도용 지원·법률비용 담보가 합성 콘텐츠 피해에 연결되는지 확인합니다.',
    evidenceNeeded: '딥페이크 탐지율, 피해자 과실 판단, 금융기관 인증 단계별 회수율 자료',
  }),
  'urban-flooding': seed({
    overview: '도시 침수·지하공간 피해',
    background: '집중호우와 불투수면 증가로 짧은 시간에 지하주차장·상가·도로에 물이 유입될 수 있습니다.',
    mechanism: '강우량·배수 용량·펌프·차수시설의 불일치가 침수와 지역적 손해 집적으로 이어지는 구조',
    damage: '건물·차량·설비 침수, 재고 손실, 영업 중단과 대피 비용',
    exposure: '건물 소유자·관리자·지자체·상가 임차인·차량 소유자',
    productIssue: '자연재해와 시설관리 과실, 침수 수위·발생 시각·피해 범위를 객관적으로 측정하는 것',
    incident: '짧은 시간의 집중호우로 배수·차수시설이 감당하지 못해 지하공간에 물이 유입되면',
    escalation: '전기설비 차단·대피·폐쇄와 지역 내 다수 건물의 동시 복구가 필요해지면',
    insuranceBoundary: '풍수해·재산·시설소유자배상책임·영업중단 담보의 원인과 면책, 정부 지원과의 중복을 확인합니다.',
    responsibility: '건물 소유자·관리자, 시설 시공·관리업체, 지자체, 임차인',
    management: '건물 관리자와 지자체가 배수·차수·펌프 점검, 기상 경보와 대피를 관리합니다.',
    customerImpact: '거주자·상가 임차인·방문객·차량 소유자와 인접 시설이 피해를 받을 수 있습니다.',
    existingInsurance: '재산·풍수해보험과 영업중단 담보가 연결될 수 있으나 지하공간, 차량, 관리상 과실의 조건을 구분해야 합니다.',
    additionalInsurance: '시설배상책임·환경오염·재난복구 비용이 기존 재산 담보와 어떻게 결합되는지 확인합니다.',
    evidenceNeeded: '강우량·침수 수위·배수 용량과 건물·차량·영업중단 손해를 연결한 자료',
  }),
  'enterprise-ransomware': seed({
    overview: '기업 랜섬웨어 공격',
    background: '공급망·원격접속·클라우드 의존도가 높아져 한 번의 침해가 여러 시스템으로 확산될 수 있습니다.',
    mechanism: '계정 탈취·취약점 악용·권한 상승 후 데이터를 암호화하거나 유출을 빌미로 금전을 요구하는 구조',
    damage: '시스템 복구·데이터 조사·고객 통지·법률 대응과 영업 중단 손해',
    exposure: '기업·공공기관·클라우드 사업자·IT 외주사·고객 데이터 주체',
    productIssue: '사이버 공격 자체와 보안관리 미흡, 데이터 유출·복구·갈취 비용을 분리하는 것',
    incident: '공격자가 업무 계정이나 취약한 외부 접점을 통해 내부 시스템에 침투하면',
    escalation: '백업까지 훼손되거나 공급망 서비스가 중단되어 다수 고객의 업무가 멈추면',
    insuranceBoundary: '사이버보험의 사고 대응·복구·배상·영업중단·갈취 비용과 기존 재산·배상책임의 경계를 확인합니다.',
    responsibility: '피보험 기업, IT·클라우드 외주사, 보안관리자, 공격자, 데이터 처리 위탁자',
    management: '기업과 위탁사가 MFA·패치·백업·권한관리·침해대응 훈련과 로그 보존을 운영합니다.',
    customerImpact: '기업 임직원·고객·거래처와 서비스에 의존하는 제3자가 손해를 받을 수 있습니다.',
    existingInsurance: '일반 배상책임·재산보험은 사이버 사고의 복구·통지·영업중단을 모두 담보하지 않을 수 있어 약관 확인이 필요합니다.',
    additionalInsurance: '사이버보험과 전문직업배상, 개인정보 유출 대응 비용의 중복·공백을 확인합니다.',
    evidenceNeeded: '침해 빈도·복구 기간·사고당 비용·업종별 집적 위험과 통제 성숙도 자료',
  }),
  'ess-ups-battery-fire': seed({
    overview: 'ESS·UPS 배터리 화재',
    background: '데이터센터·공장·재생에너지 설비의 저장장치가 대형화되며 장시간 운영·집적 위험이 커지고 있습니다.',
    mechanism: '셀 결함·열관리·충전제어·설치환경의 문제가 열폭주와 소화·재가동 지연으로 이어지는 구조',
    damage: '배터리·설비 소실, 건물·인접 설비 손상, 데이터센터·공장 가동 중단',
    exposure: 'ESS·UPS 소유자·운영자·배터리 제조사·시공·유지보수 업체',
    productIssue: '배터리 결함과 설치·운영·소방관리 원인을 구분하고 장기 중단 손해를 측정하는 것',
    incident: '저장장치 내부 이상이 열폭주·화재로 이어지면',
    escalation: '재발화 우려와 안전조사로 설비 격리·교체·가동 중단이 장기화되면',
    insuranceBoundary: '재산·기계·기업휴지·시설배상책임과 제조물책임의 원인·면책·복구 범위를 확인합니다.',
    responsibility: '설비 소유자·운영자, 배터리·PCS 제조사, 시공·유지보수 업체, 소방·안전 관리자',
    management: '운영자와 유지보수 업체가 BMS 경보·열화·충전상태·소방설비·점검 이력을 관리합니다.',
    customerImpact: '설비 소유자와 입주 기업, 인접 시설·근로자·지역 주민이 피해를 받을 수 있습니다.',
    existingInsurance: '재산·기계·기업휴지보험이 연결될 수 있으나 배터리 결함, 소화수, 재발화와 장기 중단의 조건을 확인해야 합니다.',
    additionalInsurance: '제조물책임·시설배상책임·환경·오염 정화 비용의 연결 가능성을 확인합니다.',
    evidenceNeeded: '설비 용량·운영시간 대비 화재율, 원인별 손해액, 복구기간과 집적 위험 자료',
  }),
  'heatwave-health-income-loss': seed({
    overview: '폭염에 따른 건강·소득 손실',
    background: '고온 일수가 늘면서 야외·이동·고령 노동자의 건강과 소득 중단 위험이 커지고 있습니다.',
    mechanism: '기온·습도·작업강도·휴식 부족이 온열질환과 근로 중단으로 이어지는 구조',
    damage: '치료비·휴업·소득 감소와 가족 돌봄·대체 인력 비용',
    exposure: '야외근로자·배달·건설·농업 종사자·고령자와 고용주',
    productIssue: '기후 노출과 개인 건강 요인, 업무상 재해와 일반 질환을 구분하는 것',
    incident: '고온 환경에서 온열질환이나 탈수로 치료·휴식이 필요해지면',
    escalation: '반복적인 폭염으로 근로일 손실과 대체 인력·가계 소득 감소가 누적되면',
    insuranceBoundary: '상해·질병·산재·소득보장 담보의 사고 정의와 대기기간, 중복 지급 조건을 확인합니다.',
    responsibility: '근로자·플랫폼·고용주·현장 관리자·작업 발주자',
    management: '고용주와 현장 관리자가 작업시간 조정·휴식·수분·그늘·기상 모니터링을 운영합니다.',
    customerImpact: '근로자와 가족, 인력 공백을 부담하는 사업주와 서비스 이용자가 영향을 받을 수 있습니다.',
    existingInsurance: '산재·상해·질병보험과 연결될 수 있으나 업무상 원인과 개인 질환, 소득 손실의 증빙을 확인해야 합니다.',
    additionalInsurance: '소득보장·단체상해·기후지수형 상품의 적용 가능성과 도덕적 해이 통제를 검토합니다.',
    evidenceNeeded: '기온·습도·작업강도·휴식 이력과 온열질환·근로손실을 연결한 자료',
  }),
  'platform-worker-transit-accident': seed({
    overview: '플랫폼 노동자 이동 중 사고',
    background: '배달·대리·이동 플랫폼의 업무가 늘면서 이동 중 사고의 고용·계약 경계가 복잡해지고 있습니다.',
    mechanism: '배차 압박·도로 노출·개인 이동수단 사용이 사고와 보상 책임의 분산으로 이어지는 구조',
    damage: '근로자 상해·소득 중단, 제3자 대인·대물 손해와 운송 지연',
    exposure: '배달·대리·플랫폼 종사자·플랫폼 사업자·가맹점·이용자',
    productIssue: '업무 중 사고와 개인 이동 중 사고, 플랫폼·가맹점·종사자의 책임을 구분하는 것',
    incident: '업무 배차를 수행하는 이동 중 충돌·낙상·제3자 사고가 발생하면',
    escalation: '치료와 휴업이 길어지고 플랫폼·가맹점·차량 소유자 사이 분쟁이 이어지면',
    insuranceBoundary: '자동차·상해·산재·배상책임보험의 피보험자와 업무 중 보장 범위를 확인합니다.',
    responsibility: '플랫폼 사업자·종사자·가맹점·차량 소유자·도로 이용자',
    management: '플랫폼과 가맹점이 배차·안전교육·운행수단·사고 접수와 종사자 보호 절차를 관리합니다.',
    customerImpact: '종사자와 가족, 사고 상대방·보행자·음식점·서비스 이용자가 피해를 받을 수 있습니다.',
    existingInsurance: '자동차·상해·배상책임 담보가 연결될 수 있으나 업무성, 중복 보장, 개인 차량 사용 조건을 확인해야 합니다.',
    additionalInsurance: '플랫폼 단체상해·운송배상·사용자책임의 결합과 책임 분담을 검토합니다.',
    evidenceNeeded: '배차시간·주행거리 대비 사고율, 업무성 판단 기준과 사고당 치료·소득 손해 자료',
  }),
  'ai-transparency-obligation': seed({
    overview: '생성형 AI 투명성 의무 대응',
    background: '기업의 AI 활용이 일상화되면서 생성물 표시·고지와 이용자 설명 책임이 구체화되고 있습니다.',
    mechanism: 'AI 사용 사실·생성물 표시·위험 고지·기록 관리가 누락되어 규제 위반과 고객 분쟁으로 이어지는 구조',
    damage: '시정·과징금 대응 비용, 서비스 수정·중단, 고객 신뢰 하락과 계약상 손해',
    exposure: 'AI 서비스 사업자·도입 기업·콘텐츠 제작사·이용자·위탁 개발사',
    productIssue: '법적 의무 위반과 단순 품질 오류, 고지·통제 부족으로 인한 손해를 구분하는 것',
    incident: 'AI 생성물 표시나 이용자 고지가 누락되어 감독기관·고객의 문제 제기가 발생하면',
    escalation: '콘텐츠 회수·서비스 수정·조사 대응과 다수 이용자에 대한 재통지가 필요해지면',
    insuranceBoundary: '사이버·전문직업배상·경영책임 담보가 규제 대응 비용과 제3자 손해에 연결되는지 확인합니다.',
    responsibility: 'AI 서비스 사업자·도입 기업·개발·운영 위탁사·콘텐츠 담당자',
    management: '기업이 모델 목록·사용 목적·고지 문구·생성물 표시·검토·로그 보존을 관리합니다.',
    customerImpact: 'AI 결과에 의존하는 고객·이용자와 생성물을 배포하는 거래 상대방이 영향을 받을 수 있습니다.',
    existingInsurance: '전문직업·사이버·경영책임보험의 적용 가능성이 있으나 행정제재·고의·계약상 손해 면책을 확인해야 합니다.',
    additionalInsurance: 'AI 오류·규제 대응·콘텐츠 배상과 방어비용을 별도 특약으로 구조화할 수 있는지 검토합니다.',
    evidenceNeeded: '의무 대상·시행 시점·고지 이행 로그와 AI 오류·규제 대응 비용 자료',
  }),
  'mydata-portability-demand': seed({
    overview: '전 분야 마이데이터 전송사고',
    background: '개인정보 전송요구권 확대로 기관 간 데이터 이동과 제3자 서비스 연계가 늘고 있습니다.',
    mechanism: '동의·인증·API 매핑·전송·삭제 단계 중 오류가 발생해 오수신·과다 제공·잔존 데이터가 생기는 구조',
    damage: '개인정보 유출·오전송, 통지·조사·복구 비용과 고객 이탈',
    exposure: '정보주체·정보 제공자·마이데이터 사업자·중계기관·정보 수신자',
    productIssue: '전송 오류와 관리상 과실, 데이터 주체·수신자의 책임 및 손해를 구분하는 것',
    incident: '동의 범위를 벗어난 데이터가 잘못된 수신자에게 전송되거나 삭제되지 않으면',
    escalation: '다수 이용자의 데이터가 연쇄적으로 노출되어 통지·조사·서비스 중단이 필요해지면',
    insuranceBoundary: '사이버·개인정보 배상·전문직업배상 담보의 사고 정의와 정보 주체별 배상 범위를 확인합니다.',
    responsibility: '정보 제공자·전송사업자·중계기관·정보 수신자·위탁 개발사',
    management: '각 기관이 동의 범위·인증·API 권한·전송 검증·철회·삭제 로그를 관리합니다.',
    customerImpact: '정보주체와 정보 이동 서비스를 이용하는 고객, 데이터에 의존하는 제휴사가 피해를 받을 수 있습니다.',
    existingInsurance: '사이버·개인정보 배상보험이 연결될 수 있으나 전송 오류, 규제기관 제재와 고의·중과실 조건을 확인해야 합니다.',
    additionalInsurance: '전문직업배상·위탁자 책임·통지·신용 모니터링 비용의 결합 가능성을 검토합니다.',
    evidenceNeeded: '전송 건수·오류율·정보 유형별 손해·철회 후 잔존 데이터와 사고 대응 비용 자료',
  }),
  'heatwave-workplace-duty': seed({
    overview: '폭염 작업장 온열질환 의무',
    background: '폭염이 반복되면서 사업주의 작업중지·휴식·보냉조치와 기록 의무가 중요해지고 있습니다.',
    mechanism: '작업환경 측정·위험성 평가·휴식·수분·응급조치가 미흡해 근로자 온열질환으로 이어지는 구조',
    damage: '근로자 치료·장해·사망 손해와 사업주의 산재·민사·행정 대응 비용',
    exposure: '건설·물류·농업·제조 사업주와 현장 근로자·도급업체',
    productIssue: '사업주의 예방조치 이행과 업무상 재해, 개인 건강요인을 증빙으로 구분하는 것',
    incident: '사업장에서 고온 노출 중 온열질환이 발생해 치료·작업중지가 필요해지면',
    escalation: '도급·교대 현장 전체의 작업 중단과 조사, 추가 피해자 발생이 이어지면',
    insuranceBoundary: '산재·근로자재해·사용자배상책임과 법정 의무 이행 여부의 관계를 확인합니다.',
    responsibility: '사업주·원청·도급업체·현장 관리자·근로자',
    management: '사업주와 원청이 기상·작업강도·휴식·수분·보냉·응급 이력과 교육을 관리합니다.',
    customerImpact: '근로자와 가족, 작업중단·도급 지연을 부담하는 사업주와 발주자가 영향을 받을 수 있습니다.',
    existingInsurance: '산재·근로자재해·사용자배상책임에 연결될 수 있으나 의무 위반과 고의·중과실의 범위를 확인해야 합니다.',
    additionalInsurance: '단체상해·사용자배상·기후지수형 보장과 예방 통제 조건의 결합 가능성을 검토합니다.',
    evidenceNeeded: '작업환경·휴식·보냉조치·교육 기록과 온열질환 사고·손해 자료',
  }),
  'kuam-urban-pilot': seed({
    overview: 'K-UAM 도심 실증 운항사고',
    background: '도심항공교통 실증으로 운항·교통관리·버티포트가 하나의 운영망으로 연결되고 있습니다.',
    mechanism: '기체·운항·관제·버티포트·통신의 상호작용이 실패해 공중·지상 제3자 위험으로 이어지는 구조',
    damage: '기체·시설 손상, 탑승자·지상 제3자 인명 손해와 운항 중단 비용',
    exposure: 'UAM 기체·운항사·교통관리자·버티포트 운영자·탑승자·지상 제3자',
    productIssue: '실증 단계의 책임 주체와 운항 중단·제3자 손해의 보상 한도를 정하는 것',
    incident: '운항·관제·착륙 과정에서 기체 이상이나 경로 이탈이 발생하면',
    escalation: '공역 통제·시설 폐쇄·조사로 해당 노선과 운영망 전체가 중단되면',
    insuranceBoundary: '항공보험·운항자배상·시설소유자배상·제조물책임의 책임 구간과 보상한도를 확인합니다.',
    responsibility: '운항사·기체 제조사·교통관리자·버티포트 운영자·정비업체',
    management: '운항·정비·관제·버티포트 운영 주체가 운항 승인·기상·통신·비상 착륙 절차를 관리합니다.',
    customerImpact: '탑승자·지상 보행자·인접 건물·시설 운영자와 서비스 이용자가 피해를 받을 수 있습니다.',
    existingInsurance: '항공·배상책임 담보가 연결될 수 있으나 실증 단계의 면책·운항 중단·관제 책임을 확인해야 합니다.',
    additionalInsurance: '전문직업·시설·제조물책임을 운항 단계별로 결합하는 구조를 검토합니다.',
    evidenceNeeded: '운항 횟수·비행시간 대비 사고·준사고율, 주체별 책임·보상한도 자료',
  }),
  'ai-voice-investigation': seed({
    overview: 'AI 음성복제 금융사기',
    background: '음성복제 사기 탐지와 수사 지원 체계가 도입될 만큼 사칭 방식이 정교해지고 있습니다.',
    mechanism: '짧은 음성 샘플을 복제해 가족·상사처럼 접근하고 비밀번호·송금·인증을 유도하는 구조',
    damage: '송금액·계정 탈취·거래 정지에 따른 자금 손실과 회수·수사 비용',
    exposure: '개인 고객·기업 재무담당자·금융기관·콜센터·가족·거래처',
    productIssue: '복제 음성 여부, 피해자 확인 절차, 금융기관 이상거래 탐지와 책임을 구분하는 것',
    incident: '복제된 음성이 지인·상사의 요청으로 믿어져 송금이나 인증이 실행되면',
    escalation: '추가 계정 탈취와 다수 거래 중지·신고·수사 대응이 이어지면',
    insuranceBoundary: '전자금융·금융사기·사이버 담보의 피해자 과실과 본인확인 절차 적용 여부를 확인합니다.',
    responsibility: '사기범·피해자·금융기관·통신·플랫폼 사업자·기업 승인권자',
    management: '금융기관과 기업이 다중 인증·콜백·이상거래 탐지·거래 지연·직원 교육을 관리합니다.',
    customerImpact: '개인·기업의 송금자와 계좌 명의자, 거래 상대방·가족이 피해를 받을 수 있습니다.',
    existingInsurance: '금융사기·전자금융 담보가 연결될 수 있으나 사회공학적 사칭, 본인 인증, 피해자 중과실 조건을 확인해야 합니다.',
    additionalInsurance: '신원도용 지원·사이버·법률비용 담보가 음성복제 피해에 연결되는지 검토합니다.',
    evidenceNeeded: '음성복제 탐지율·피해 회수율·인증 단계별 사고와 피해자 과실 판단 자료',
  }),
  'medical-liability-insurance': seed({
    overview: '의료기관 책임보험 가입 의무',
    background: '의료사고 피해구제 제도 변화로 일정 의료기관의 책임보험·공제 가입과 관리가 중요해지고 있습니다.',
    mechanism: '진료·수술·설명·기록 과정의 오류가 환자 손해와 의료분쟁·조정·소송으로 이어지는 구조',
    damage: '환자 치료·장해·사망 배상과 의료기관의 방어·조정·운영 중단 비용',
    exposure: '보건의료기관·의료인·환자·의료기기·위탁검사·책임보험자',
    productIssue: '의료행위상 과실·불가피한 합병증·설명 의무와 법정 가입 한도를 구분하는 것',
    incident: '진료 과정에서 환자에게 예기치 않은 손해가 발생해 배상·조정 절차가 시작되면',
    escalation: '중대한 장해·사망으로 장기 치료와 소송, 기관 운영·평판 손해가 이어지면',
    insuranceBoundary: '의료배상책임·전문직업배상·시설·근로자 담보의 피보험자와 보상 한도를 확인합니다.',
    responsibility: '의료기관 개설자·의료인·간호·검사 인력·의료기기·위탁기관',
    management: '의료기관이 자격·동의·수술 체크리스트·기록·사고 보고·환자 설명을 관리합니다.',
    customerImpact: '환자와 가족, 의료기관·의료인·위탁검사기관이 손해와 분쟁 비용을 부담할 수 있습니다.',
    existingInsurance: '의료배상책임보험·공제와 연결될 수 있으나 가입 의무 대상·한도·면책·소급기간을 확인해야 합니다.',
    additionalInsurance: '전문직업배상·법률비용·환자지원 비용을 법정 책임보험과 결합하는 구조를 검토합니다.',
    evidenceNeeded: '대상 기관·시행령 한도·사고 유형별 빈도·평균 배상액과 방어비용 자료',
  }),
  'sns-impersonation-commerce': seed({
    overview: 'SNS 사칭 쇼핑몰 미배송·가품',
    background: 'SNS 광고와 간편결제로 소비자가 실제 사업자 여부를 확인하기 전에 거래가 완료될 수 있습니다.',
    mechanism: '유명 브랜드·공식 계정을 사칭한 할인 광고가 결제·개인정보 입력을 유도한 뒤 미배송·가품으로 이어지는 구조',
    damage: '상품 대금·배송비 손실, 개인정보 노출, 결제 취소·차지백과 신고 비용',
    exposure: '소비자·브랜드 권리자·SNS 플랫폼·결제사업자·사칭 쇼핑몰',
    productIssue: '판매자 실재성·플랫폼 감시·결제 승인·소비자 확인의 책임을 구분하는 것',
    incident: '사칭 광고를 통해 소비자가 결제했지만 상품이 배송되지 않거나 가품이 도착하면',
    escalation: '다수 구매자 피해와 계정·카드정보 노출, 환불·분쟁·브랜드 복구가 이어지면',
    insuranceBoundary: '전자상거래·사이버·결제보호·법률비용 담보의 소비자 피해 적용 여부를 확인합니다.',
    responsibility: '사칭 판매자·SNS 플랫폼·결제사업자·브랜드 권리자·소비자',
    management: '플랫폼과 결제사업자가 광고·판매자 인증·신고·거래 중지·환불 절차를 관리합니다.',
    customerImpact: '소비자와 브랜드 권리자, 결제사업자·플랫폼의 고객지원 조직이 피해를 경험할 수 있습니다.',
    existingInsurance: '전자상거래·사이버·배상책임 담보가 연결될 수 있으나 사기 자체와 플랫폼·결제사업자의 법적 책임을 확인해야 합니다.',
    additionalInsurance: '구매자 보호·법률비용·신원도용 지원을 플랫폼 또는 결제 단계에 결합할 수 있는지 검토합니다.',
    evidenceNeeded: '판매자 확인·광고 신고·결제 취소·차지백 결과와 피해 건당 금액 자료',
  }),
  'ota-delivery-consumer-disputes': seed({
    overview: 'OTA 항공권·택배 소비자 피해',
    background: '온라인 여행·배송 중개가 늘며 예약·운송·환불 단계의 책임 주체가 분산되고 있습니다.',
    mechanism: '취소·지연·오배송이 OTA·항공사·택배사·판매자 사이의 계약과 정보 전달 단절로 분쟁화되는 구조',
    damage: '항공권·상품 대금, 대체 운송·숙박 비용, 배송물 손상·지연과 분쟁 비용',
    exposure: '여행객·수하물·택배 수령인·OTA·항공사·택배사·판매자',
    productIssue: '계약상 환불과 실제 추가 손해, 중개사업자·운송사업자의 책임을 구분하는 것',
    incident: '예약·운송 과정에서 취소·지연·오배송이 발생해 소비자가 대체 비용을 부담하면',
    escalation: '성수기 다수 예약·배송이 동시에 차질을 빚어 환불·민원·대체 운송이 누적되면',
    insuranceBoundary: '여행·적재물·운송배상·전자상거래 담보의 지연·취소·오배송 보장 조건을 확인합니다.',
    responsibility: 'OTA·항공사·택배사·판매자·운송 위탁사·소비자',
    management: '중개·운송사업자가 예약·운송 상태·취소 고지·환불·분실·사고 접수 이력을 관리합니다.',
    customerImpact: '여행객·수령인과 판매자, 항공사·택배사의 고객지원·분쟁 대응 조직이 영향을 받을 수 있습니다.',
    existingInsurance: '여행·운송·적재물·배상책임 담보가 연결될 수 있으나 계약상 환불과 실제 손해의 경계를 확인해야 합니다.',
    additionalInsurance: '지연·취소·분실을 지수 또는 영수증 기반으로 보장하는 제한적 특약 가능성을 검토합니다.',
    evidenceNeeded: '거래 단계별 취소·지연·오배송 빈도, 환불·대체 비용과 책임 인정 기준 자료',
  }),
}

export function getRiskDetailNarrative(riskId: string): RiskDetailNarrative | undefined {
  return detailNarratives[riskId]
}
