import type { RiskLawTrackingItem } from './riskLawTracking'

const medicalPrecedent = {
  type: '대법원 판결 · 의료행위상 주의의무',
  caseNumber: '2016다266606',
  title: '의료과실과 인과관계·손해배상액 산정',
  badge: '대법원 2018. 11. 29. 선고',
  issue: '의료행위상 주의의무 위반과 결과 사이의 인과관계, 환자의 체질적 소인 등을 손해배상액에 반영할 수 있는지가 문제 된 사건입니다.',
  judgment: '의료수준은 당시 임상의학에서 일반적으로 알려지고 시인된 수준을 기준으로 판단하며, 의료과실과 인과관계의 증명 및 손해배상액 제한 법리를 확인했습니다.',
  award: '오른쪽 정중신경 손상에 따른 노동능력상실률 16%, 일실수입·일실퇴직금 및 위자료 1,000만 원 산정 내용이 판결에 포함됩니다.',
  sourceUrl: 'https://portal.scourt.go.kr/pgp/main.on?c=900&jisCntntsSrno=3204272&w2xPath=PGP1011M04',
}
const medicalLossCase = {
  type: '대법원 판결 · 의료사고 손해 사례',
  caseNumber: '2013다96165',
  title: '척추 수술 후 장애와 향후치료비·개호비 손해',
  badge: '대법원 2016. 7. 27. 주요판결',
  issue: '의료사고 피해자가 기왕치료비·위자료 등을 먼저 청구한 뒤 신체감정으로 확인되는 향후치료비·개호비를 추가 청구할 수 있는지가 문제 된 사건입니다.',
  judgment: '대법원은 적극적 손해에 대한 명시적 일부청구 여부를 소송 경과와 청구 내용까지 종합해 판단해야 한다고 보고 일부 파기환송했습니다.',
  award: '선행 소송에서 적극적 손해와 위자료 합계 약 8,000만 원을 청구한 사실 및 추가 향후치료비·개호비 청구가 판결 요지에 기재되어 있습니다.',
  sourceUrl: 'https://www.scourt.go.kr/portal/news/NewsViewAction.work?currentPage=2&gubun=4&searchOption=&searchWord=&seqnum=5282',
}

const firePrecedent = {
  type: '서울북부지방법원 판결 · 화재 손해배상',
  caseNumber: '2024가합22263',
  title: '간이창고 화재의 공작물 하자와 인접 건물 연소 손해',
  badge: '서울북부지방법원 2025. 8. 14. 선고',
  issue: '담배꽁초에서 시작된 불이 가연성 물질이 보관된 간이창고와 인접 건물로 확산된 경우, 발화행위자와 건물 소유자의 공동 책임이 문제 된 사건입니다.',
  judgment: '발화행위자의 불법행위책임과 간이창고의 설치·보존상 하자에 따른 공작물책임을 인정하고, 피해 건물의 화재 취약성 등 과실을 함께 고려했습니다.',
  award: '피고들의 손해배상책임을 피해 확대 원인과 손해분담의 형평성을 고려해 50%로 제한했습니다.',
  sourceUrl: 'https://www.scourt.go.kr/portal/dcboard/DcNewsViewAction.work?cbub_code=000213&gubun=44&scode_kname=&searchOption=&searchWord=&seqnum=27348',
}

const fireLossCase = {
  type: '법원 공개 손해 사례 · 화재 확산',
  caseNumber: '2024가합22263 · 실제 피해 사실',
  title: '인접 건물 2동 전소 및 시설·집기·동산 소실',
  badge: '법원 공개 판결문 기반',
  issue: '간이창고 화재가 인접한 원고 소유 건물 2동으로 번지면서 건물과 보관 중인 시설·집기비품·동산이 소실된 사례입니다.',
  judgment: '화재 원인, 연소 확산, 피해 대상과 정도가 법원 판단의 손해 범위 검토 자료로 확인됩니다.',
  award: '구체적 손해액은 공개 판결문과 손해자료 원문을 대조해야 하며, 책임비율은 50%로 판단되었습니다.',
  sourceUrl: 'https://www.scourt.go.kr/portal/dcboard/DcNewsViewAction.work?cbub_code=000213&gubun=44&scode_kname=&searchOption=&searchWord=&seqnum=27348',
}

const evLossCase = {
  type: '소방청 통계 · 국가화재정보시스템',
  caseNumber: '2020–2024 전기차 화재 223건',
  title: '전기차 화재 발생 증가와 진압·손해확인 공백',
  badge: '소방청 2025. 1. 15. 공개 자료',
  issue: '소방청 국가화재정보시스템 자료에서 최근 5년간 전기차 화재 223건이 집계되어 차량·충전시설·주차장 제3자 손해의 누적 노출을 확인할 수 있습니다.',
  judgment: '공개 통계는 화재 빈도와 추세를 보여주지만 개별 사고의 제조물 결함, 책임 주체, 보험 손해액을 확정하지 않으므로 사고별 원인·손해자료가 추가로 필요합니다.',
  award: '공개 통계에는 개별 손해액이 포함되지 않습니다. 사고별 재산손해·대물손해·영업중단 손해 원문 확인 필요',
  sourceUrl: 'https://www.nfa.go.kr/nfa/news/pressrelease/press/?cntId=2577&mode=view',
}

const aiPrecedent = {
  type: '미국 캘리포니아 북부연방지방법원',
  caseNumber: '3:23-cv-03417-VC',
  title: 'Kadrey et al. v. Meta Platforms, Inc.',
  badge: '2025. 6. 25. 부분적 summary judgment',
  issue: '저작권 보호 저작물을 생성형 AI 학습에 복제한 행위의 공정이용과 저작권자의 잠재적 라이선스 시장 손해가 문제 된 사건입니다.',
  judgment: '법원은 원고들이 AI 학습으로 인한 시장손해를 충분히 입증하지 못했다고 보았지만, 해당 판단이 AI 학습 전반의 적법성을 선언한 것은 아니라고 설명했습니다.',
  award: '해당 판결에서 원고에 대한 손해배상액은 확정되지 않았습니다. 국내 저작권법 적용은 별도 검토가 필요합니다.',
  sourceUrl: 'https://cand.uscourts.gov/cases-e-filing/cases/323-cv-03417-vc/kadrey-et-al-v-meta-platforms-inc',
}

const aiLossCase = {
  type: '미국 캘리포니아 북부연방지방법원 · 집단합의',
  caseNumber: '3:24-cv-05417-AMO',
  title: 'Bartz et al. v. Anthropic PBC',
  badge: '2026. 7. 법원 승인 기록',
  issue: '저작권 보호 도서를 불법 취득·복제하여 AI 학습에 사용했다는 작가·출판권자 측의 손해배상 청구와 집단합의가 문제 된 사건입니다.',
  judgment: '법원 기록에는 비환급성 합의기금 15억 달러와 저작권자·출판권자에 대한 분배 구조가 기재되어 있습니다. 이는 미국 사건의 합의 결과이며 국내 책임이나 보험금 지급을 의미하지 않습니다.',
  award: '합의기금 15억 달러 + 이자. 개별 권리자 지급액은 청구·작품 확인 절차에 따라 달라집니다.',
  sourceUrl: 'https://cand.uscourts.gov/cases-e-filing/cases/324-cv-05417-amo/bartz-et-al-v-anthropic-pbc',
}

export const verifiedRiskLawTrackingOverrides: Record<string, Partial<RiskLawTrackingItem>> = {
  'law-medical-liability-insurance': {
    relatedCaseCount: 1,
    relatedLossCount: 1,
    relatedCases: [medicalPrecedent],
    relatedLossCases: [medicalLossCase],
    checklist: ['법률 제·개정문과 2027. 5. 27. 시행일 확인', '2016다266606·2013다96165 판결의 과실·인과관계·손해액 판단을 별도 검토', '보험 가입 의무와 실제 보상범위·보험료는 하위법령과 약관 확인'],
    evidenceIds: ['LAW-MEDICAL-LIABILITY-20260526', 'SC-2016다266606', 'SC-2013다96165'],
    insuranceClauseCandidates: [
      {
        title: '가입 대상·가입 형태',
        status: '법령 연결',
        detail: '보건의료기관개설자를 피보험자 범위로 두고 책임보험 또는 책임공제 중 어떤 방식으로 가입했는지 증빙하도록 구성합니다.',
        sourceLabel: '국가법령정보센터 제47조 원문',
        sourceUrl: 'https://www.law.go.kr/LSW/lsInfoP.do?ancNo=21694&ancYd=20260526&efYd=20270527&lsiSeq=286221',
      },
      {
        title: '보상하는 손해·사고 정의',
        status: '법령 연결',
        detail: '의료사고로 발생한 생명·신체·재산 손해와 손해배상금의 범위를 연결하되, 의료행위·피해 결과·책임 인정의 판단 기준은 약관에서 구체화해야 합니다.',
        sourceLabel: '국가법령정보센터 손해배상액 결정 기준',
        sourceUrl: 'https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=286221&efYd=20270527',
      },
      {
        title: '보험금 지급·대불 연계',
        status: '하위법령 확인',
        detail: '손해배상금 지급 절차와 대불 제도를 연결하고, 조정·중재비용과 소송비용은 대불 대상에서 제외되는지 별도 구분해 약관에 반영합니다.',
        sourceLabel: '의료분쟁조정법 시행령 제25조 원문',
        sourceUrl: 'https://www.law.go.kr/LSW/lsInfoP.do?ancYnChk=0&chrClsCd=010202&efYd=20260102&lsiSeq=281593&urlMode=lsInfoP',
      },
      {
        title: '가입금액·보상한도',
        status: '하위법령 확인',
        detail: '연간 배상한도액과 기관별 가입금액은 법률 본문만으로 확정하지 않고 대통령령·하위 기준의 최신 원문을 확인한 뒤 정합니다.',
        sourceLabel: '개정 법률·시행 준비 조문',
        sourceUrl: 'https://law.go.kr/LSW/lsRvsDocListP.do?chrClsCd=010202&lsId=011585&lsRvsGubun=all',
      },
      {
        title: '면책·고의·중대한 과실',
        status: '약관 설계 검토',
        detail: '고의 행위, 중대한 과실, 설명의무 위반, 기관 외부 의료인의 행위처럼 책임과 보상 범위가 갈리는 항목은 법령 확정값으로 단정하지 않고 약관·판례 검토 항목으로 둡니다.',
        sourceLabel: '대법원 의료과실·인과관계 판례',
        sourceUrl: 'https://portal.scourt.go.kr/pgp/main.on?c=900&jisCntntsSrno=3204272&w2xPath=PGP1011M04',
      },
      {
        title: '사고 통지·자료 제출·분쟁 대응',
        status: '약관 설계 검토',
        detail: '사고 통지 시점, 진료기록·감정자료 제출, 조정·중재 절차 협조, 합의·소송 전 보험자 동의 여부를 실제 보험금 청구 흐름에 맞춰 정합니다.',
        sourceLabel: '보건복지부 의료사고 안전망 정책 원문',
        sourceUrl: 'https://www.mohw.go.kr/menu.es?mid=a10715020400',
      },
    ],
  },
  'law-disaster-mandatory-insurance-standard': {
    relatedCaseCount: 1,
    relatedLossCount: 1,
    relatedCases: [firePrecedent],
    relatedLossCases: [fireLossCase],
    checklist: ['재난안전법 제76조의2와 2026. 1. 27. 업무기준의 보상한도·가입자 관리 기준 확인', '2024가합22263 판결에서 인정된 발화·공작물 하자·피해자 과실 구조 확인', '재난안전의무보험별 실제 가입대상·보상한도·중복보상 여부 확인'],
    evidenceIds: ['LAW-DISASTER-MANDATORY-20260127', 'SC-2024가합22263'],
    insuranceClauseCandidates: [
      { title: '가입 대상·보험 종목', status: '법령 연결', detail: '재난안전의무보험은 개별 법률이 정한 가입자·시설·영업 유형을 기준으로 피보험자와 보험 종목을 확정해야 하며, 모든 재난 위험을 하나의 상품으로 묶지 않습니다.', sourceLabel: '행정안전부 의무보험 관리·운용 기준', sourceUrl: 'https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000273718' },
      { title: '보상 범위·보상한도', status: '하위법령 확인', detail: '재난별 대인·대물·재산손해와 법정 보상한도, 자기부담금, 중복보상 조정 여부를 해당 의무보험 근거 법령과 별표에서 확인합니다.', sourceLabel: '행정안전부 의무보험 관리 원문', sourceUrl: 'https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000273718' },
      { title: '가입 확인·미가입 조치', status: '법령 연결', detail: '가입증명서 제출·갱신·변경 신고와 미가입 시 과태료·영업정지·강제징수 등 제재의 근거와 적용 주체를 약관 운영 절차에 연결합니다.', sourceLabel: '행정안전부 의무보험 관리 원문', sourceUrl: 'https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000273718' },
      { title: '사고 통지·손해사정', status: '약관 설계 검토', detail: '재난 발생 시 사고 통지, 피해 확인, 잔존물·복구비 증빙, 공적 재난지원금과 보험금의 조정 절차를 약관에 구체화합니다.', sourceLabel: '화재 손해배상 판결 원문', sourceUrl: 'https://www.scourt.go.kr/portal/dcboard/DcNewsViewAction.work?cbub_code=000213&gubun=44&scode_kname=&searchOption=&searchWord=&seqnum=27348' },
    ],
  },
  'law-ev-fire': {
    sourceType: 'administrative',
    typeLabel: '기후에너지환경부 / 정책성 보험',
    institution: '기후에너지환경부·국토교통부·소방청',
    title: '전기차 화재안심보험 및 배터리 화재 안전관리',
    summary: '2026년 전기차 주차·충전 중 제3자 대물피해를 사고당 100억 원 이상 보장하는 정책성 보험이 추진되고, 배터리 인증·이력관리·무상 안전점검이 병행됩니다.',
    status: '정책성 보험 공모·안전점검 추진',
    expectedEffectiveDate: '2026.07.01 참여 기준',
    lastUpdated: '2026.06.18',
    riskLevel: 'high',
    sourceUrl: 'https://eng.me.go.kr/home/web/board/read.do?boardCategoryId=&boardId=1848920&boardMasterId=939&decorator=&maxIndexPages=10&maxPageItems=10&menuId=10598&orgCd=&pagerOffset=280&searchKey=&searchValue=',
    relatedCaseCount: 0,
    relatedLossCount: 1,
    timeline: [
      { label: '전기차 화재안심보험 공모', stage: 'complete', date: '2026.03.12' },
      { label: '제작사·수입사 참여 기준', stage: 'complete', date: '2026.06.30' },
      { label: '미참여 업체 보조금 기준', stage: 'current', date: '2026.07.01' },
      { label: '배터리·충전시설 안전점검', stage: 'current', date: '2026.06.18' },
    ],
    beforeChanges: [
      { label: '피해 범위', value: '전기차 화재의 제3자 대물손해 책임 주체·보상재원이 사고별로 달라질 수 있음' },
      { label: '공개 손해 데이터', value: '소방청 화재 건수는 확인되지만 사고별 손해액·책임 원인은 별도 확인 필요' },
    ],
    afterChanges: [
      { label: '정책성 보험', value: '주차·충전 중 제3자 대물피해를 사고당 100억 원 이상 보장하는 기준 제시', emphasis: 'red' },
      { label: '참여 유인', value: '2026.07.01 이후 미참여 업체 차량은 전기차 보조금 대상에서 제외', emphasis: 'blue' },
      { label: '안전관리', value: '배터리 인증·이력관리와 제작사 무상 안전점검을 병행', emphasis: 'blue' },
    ],
    changeBadge: '정책성 보험·배터리 안전관리 실제 자료',
    relatedCases: [],
    relatedLossCases: [evLossCase],
    checklist: ['환경부 정책성 보험 지침의 가입대상·우선 적용 보험·보장범위 확인', '소방청 2020~2024 전기차 화재 223건 통계와 사고별 손해자료 분리', '국내 전기차 화재 판례가 확인되기 전까지 제조물 결함·충전사업자 책임을 단정하지 않음'],
    evidenceIds: ['ME-EV-FIRE-INSURANCE-20260312', 'MOLIT-EV-SAFETY-20260618', 'NFA-EV-FIRE-20250115'],
    insuranceClauseCandidates: [
      { title: '보장 대상·사고 장소', status: '법령 연결', detail: '주차·충전 중 전기차 화재로 발생한 제3자 대물손해와 시설·차량 손해를 사고 정의와 보장 대상별로 분리 검토합니다.', sourceLabel: '환경부 전기차 화재안심보험 정책 원문', sourceUrl: 'https://eng.me.go.kr/home/web/board/read.do?boardCategoryId=&boardId=1848920&boardMasterId=939&decorator=&maxIndexPages=10&maxPageItems=10&menuId=10598&orgCd=&pagerOffset=280&searchKey=&searchValue=' },
      { title: '보상한도·책임 주체', status: '하위법령 확인', detail: '사고당 보장한도와 제조사·수입사·충전사업자·주차장 운영자의 책임 분담을 정책성 보험 지침과 개별 약관에서 확인합니다.', sourceLabel: '환경부 정책성 보험 원문', sourceUrl: 'https://eng.me.go.kr/home/web/board/read.do?boardCategoryId=&boardId=1848920&boardMasterId=939&decorator=&maxIndexPages=10&maxPageItems=10&menuId=10598&orgCd=&pagerOffset=280&searchKey=&searchValue=' },
      { title: '배터리 이력·안전관리 조건', status: '약관 설계 검토', detail: '배터리 인증·이력관리·무상 안전점검 이행 여부를 가입 조건, 통지의무 또는 보험료 산정 요소로 반영할지 검토합니다.', sourceLabel: '국토교통부 전기차 안전관리 자료', sourceUrl: 'https://www.molit.go.kr/USR/NEWS/m_71/dtl.jsp?id=95091997&lcmspage=1' },
      { title: '화재 원인·손해 증빙', status: '약관 설계 검토', detail: '열폭주 원인, 충전시설 결함, 관리상 과실, 연기·시설폐쇄·영업중단 손해를 손해사정 자료로 구분합니다.', sourceLabel: '소방청 전기차 화재 통계 원문', sourceUrl: 'https://www.nfa.go.kr/nfa/news/pressrelease/press/?cntId=2577&mode=view' },
    ],
    candidateIds: ['ev-battery-fire'],
  },
  'law-ai-copyright': {
    sourceType: 'administrative',
    typeLabel: '법원·저작권 정책 자료',
    institution: '미국 캘리포니아 북부연방지방법원·대한민국 법원 IP 연구센터',
    title: '생성형 AI 학습데이터 저작권·시장손해 쟁점',
    summary: 'AI 학습데이터의 복제·취득과 잠재적 라이선스 시장 손해를 다룬 해외 판결·집단합의가 공개되어 국내 저작권·방어비용 검토의 비교자료로 연결됩니다.',
    status: '해외 판결·합의 확인 · 국내 적용 별도 검토',
    expectedEffectiveDate: '해당 없음 · 비교 판례·합의',
    lastUpdated: '2026.07',
    riskLevel: 'high',
    sourceUrl: 'https://patent.scourt.go.kr/dcboard/new/DcNewsViewAction.work?gubun=565&seqnum=99',
    relatedCaseCount: 2,
    relatedLossCount: 1,
    timeline: [
      { label: 'AI 학습 저작권 소송 제기', stage: 'complete', date: '2023~2024' },
      { label: 'Kadrey v. Meta 판결', stage: 'complete', date: '2025.06.25' },
      { label: 'Bartz v. Anthropic 집단합의', stage: 'complete', date: '2026.07' },
      { label: '국내 저작권법 적용 검토', stage: 'current', date: '국내 판례·약관 확인 필요' },
    ],
    beforeChanges: [
      { label: '학습데이터', value: '저작물 취득 경위·복제 범위·라이선스 여부를 기업별로 확인해야 함' },
      { label: '손해 범위', value: '저작권 침해 손해·라이선스 시장 손해·방어비용을 분리해야 함' },
    ],
    afterChanges: [
      { label: '비교 판례', value: 'Kadrey v. Meta가 AI 학습과 공정이용·시장손해 입증 쟁점을 제시', emphasis: 'red' },
      { label: '실제 합의', value: 'Bartz v. Anthropic에서 15억 달러 합의기금 법원 기록 확인', emphasis: 'red' },
      { label: '국내 적용', value: '해외 결과를 국내 저작권법·약관·보험 보장 판단으로 직접 확정하지 않음', emphasis: 'blue' },
    ],
    changeBadge: '해외 판결·집단합의 실제 자료',
    relatedCases: [aiPrecedent, aiLossCase],
    relatedLossCases: [aiLossCase],
    checklist: ['미국 판결·합의의 관할과 사실관계를 국내 저작권법과 분리', '학습데이터 출처·라이선스 로그와 생성 결과물의 재현 여부 확보', '저작권 손해·방어비용·영업손실의 실제 청구자료를 별도 검증'],
    evidenceIds: ['SC-IP-AI-20260227', 'US-NDCA-3-23-CV-03417-VC', 'US-NDCA-3-24-CV-05417-AMO'],
    insuranceClauseCandidates: [
      { title: '피보험자·책임 주체', status: '약관 설계 검토', detail: 'AI 개발사·서비스 제공자·도입기업·콘텐츠 제작자 중 누가 피보험자인지, 계약상 indemnity와 제3자 저작권 청구를 어떻게 구분할지 정합니다.', sourceLabel: '대한민국 법원 IP 연구센터 자료', sourceUrl: 'https://patent.scourt.go.kr/dcboard/new/DcNewsViewAction.work?gubun=565&seqnum=99' },
      { title: '보상하는 청구·방어비용', status: '법령 연결', detail: '저작권 침해 주장에 대한 법률방어비용, 조정·합의 비용, 손해배상금과 결과물 재제작·서비스 중단 비용을 담보별로 분리 검토합니다.', sourceLabel: 'Kadrey v. Meta 판결 원문', sourceUrl: 'https://cand.uscourts.gov/cases-e-filing/cases/323-cv-03417-vc/kadrey-et-al-v-meta-platforms-inc' },
      { title: '면책·고의 사용 기준', status: '약관 설계 검토', detail: '출처를 알면서 무단 사용한 경우, 라이선스 확인을 하지 않은 경우, 고의·중대한 과실이 있는 경우의 면책 기준과 입증 주체를 정합니다.', sourceLabel: 'AI 학습 저작권 판결 원문', sourceUrl: 'https://cand.uscourts.gov/cases-e-filing/cases/323-cv-03417-vc/kadrey-et-al-v-meta-platforms-inc' },
      { title: '출처·로그·손해 증빙', status: '약관 설계 검토', detail: '학습데이터 라이선스, 프롬프트·생성 이력, 사람의 검수 기록, 침해 통지와 실제 손해자료를 사고 통지·손해사정 자료로 지정합니다.', sourceLabel: 'Anthropic 집단합의 법원 기록', sourceUrl: 'https://cand.uscourts.gov/cases-e-filing/cases/324-cv-05417-amo/bartz-et-al-v-anthropic-pbc' },
    ],
    candidateIds: ['generative-ai-copyright'],
  },
  'law-virtual-asset-cyber-protection': {
    insuranceClauseCandidates: [
      { title: '가입 대상·사업자 범위', status: '법령 연결', detail: '가상자산사업자의 신고·영업 유형과 이용자 자산을 취급하는 범위를 기준으로 피보험자와 보장 대상 사업장을 확정합니다.', sourceLabel: '가상자산 이용자 보호법 제8조 원문', sourceUrl: 'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?lsJoLnkSeq=1024558691' },
      { title: '해킹·전산장애 사고 정의', status: '법령 연결', detail: '해킹, 전산장애, 지갑·키 관리 실패와 이용자 손실을 보험사고로 구분하고, 사업자 귀책 여부와 제3자 침입을 손해사정 기준으로 둡니다.', sourceLabel: '가상자산 이용자 보호법 제8조 원문', sourceUrl: 'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?lsJoLnkSeq=1024558691' },
      { title: '보험·공제·준비금 대체 기준', status: '하위법령 확인', detail: '보험 가입, 공제 가입, 준비금 적립 중 어떤 조치가 인정되는지와 사업자별 규모·최소 재원 기준을 최신 감독 기준에서 확인합니다.', sourceLabel: '가상자산 이용자 보호법 제8조 원문', sourceUrl: 'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?lsJoLnkSeq=1024558691' },
      { title: '보상한도·면책·재발 방지', status: '약관 설계 검토', detail: '이용자별 보상한도, 내부자 부정·관리자 키 분실·보안통제 미이행의 면책 여부와 사고 후 재발 방지 의무를 약관에 반영합니다.', sourceLabel: '가상자산 이용자 보호법 원문', sourceUrl: 'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?lsJoLnkSeq=1024558691' },
      { title: '사고 통지·증빙·지급 절차', status: '약관 설계 검토', detail: '침해 로그, 지갑 주소, 거래기록, 이용자별 손실액과 수사·감독기관 신고를 보험금 청구와 연결합니다.', sourceLabel: '가상자산 이용자 보호법 원문', sourceUrl: 'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?lsJoLnkSeq=1024558691' },
    ],
  },
}
